"use strict";

function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
function _slicedToArray(arr, i) { return _arrayWithHoles(arr) || _iterableToArrayLimit(arr, i) || _unsupportedIterableToArray(arr, i) || _nonIterableRest(); }
function _nonIterableRest() { throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."); }
function _unsupportedIterableToArray(o, minLen) { if (!o) return; if (typeof o === "string") return _arrayLikeToArray(o, minLen); var n = Object.prototype.toString.call(o).slice(8, -1); if (n === "Object" && o.constructor) n = o.constructor.name; if (n === "Map" || n === "Set") return Array.from(o); if (n === "Arguments" || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)) return _arrayLikeToArray(o, minLen); }
function _arrayLikeToArray(arr, len) { if (len == null || len > arr.length) len = arr.length; for (var i = 0, arr2 = new Array(len); i < len; i++) arr2[i] = arr[i]; return arr2; }
function _iterableToArrayLimit(r, l) { var t = null == r ? null : "undefined" != typeof Symbol && r[Symbol.iterator] || r["@@iterator"]; if (null != t) { var e, n, i, u, a = [], f = !0, o = !1; try { if (i = (t = t.call(r)).next, 0 === l) { if (Object(t) !== t) return; f = !1; } else for (; !(f = (e = i.call(t)).done) && (a.push(e.value), a.length !== l); f = !0); } catch (r) { o = !0, n = r; } finally { try { if (!f && null != t["return"] && (u = t["return"](), Object(u) !== u)) return; } finally { if (o) throw n; } } return a; } }
function _arrayWithHoles(arr) { if (Array.isArray(arr)) return arr; }
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, _toPropertyKey(descriptor.key), descriptor); } }
function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); Object.defineProperty(Constructor, "prototype", { writable: false }); return Constructor; }
function _toPropertyKey(arg) { var key = _toPrimitive(arg, "string"); return _typeof(key) === "symbol" ? key : String(key); }
function _toPrimitive(input, hint) { if (_typeof(input) !== "object" || input === null) return input; var prim = input[Symbol.toPrimitive]; if (prim !== undefined) { var res = prim.call(input, hint || "default"); if (_typeof(res) !== "object") return res; throw new TypeError("@@toPrimitive must return a primitive value."); } return (hint === "string" ? String : Number)(input); }
// Generated by CoffeeScript 2.7.0
(function () {
  var CELL_SIZE,
    Jelly,
    JellyCell,
    Stage,
    Wall,
    i,
    k,
    level,
    levelPicker,
    levels,
    moveToCell,
    option,
    ref,
    stage,
    indexOf = [].indexOf;
  levels = [
  // Level 1
  ["xxxxxxxxxxxxxx", "x            x", "x            x", "x      r     x", "x      xx    x", "x  g     r b x", "xxbxxxg xxxxxx", "xxxxxxxxxxxxxx"], ["xxxxxxxxxxxxxx", "x            x", "x            x", "x            x", "x     g   g  x", "x   r r   r  x", "xxxxx x x xxxx", "xxxxxxxxxxxxxx"], ["xxxxxxxxxxxxxx", "x            x", "x            x", "x   bg  x g  x", "xxx xxxrxxx  x", "x      b     x", "xxx xxxrxxxxxx", "xxxxxxxxxxxxxx"], ["xxxxxxxxxxxxxx", "x            x", "x       r    x", "x       b    x", "x       x    x", "x b r        x", "x b r      b x", "xxx x      xxx", "xxxxx xxxxxxxx", "xxxxxxxxxxxxxx"],
  // Level 5
  ["xxxxxxxxxxxxxx", "x            x", "x            x", "xrg  gg      x", "xxx xxxx xx  x", "xrg          x", "xxxxx  xx   xx", "xxxxxx xx  xxx", "xxxxxxxxxxxxxx"], ["xxxxxxxxxxxxxx", "xxxxxxx      x", "xxxxxxx g    x", "x       xx   x", "x r   b      x", "x x xxx x g  x", "x         x bx", "x       r xxxx", "x   xxxxxxxxxx", "xxxxxxxxxxxxxx"], [
  // Anchored jellies are specified separately after the
  // level map. Instead of [row, row, row...in the presence of
  // anchors the level specification is:
  // [ [row,row,row...], [ anchor, anchor, anchor...] ].
  // Each anchor starts from a colored non-black jelly's
  // coordinates and specifies the direction in which it's "held".
  ["xxxxxxxxxxxxxx", "x            x", "x          r x", "x          x x", "x     b   b  x", "x     x  rr  x", "x         x  x", "x r  bx x x  x", "x x  xx x x  x", "xxxxxxxxxxxxxx"], [{
    x: 2,
    y: 7,
    dir: 'down'
  }, {
    x: 5,
    y: 7,
    dir: 'down'
  }]], [["xxxxxxxxxxxxxx", "xxxx x  x xxxx", "xxx  g  b  xxx", "xx   x  x   xx", "xx   b  g   xx", "xxg        bxx", "xxxg      bxxx", "xxxx      xxxx", "xxxxxxxxxxxxxx"], [{
    x: 5,
    y: 4,
    dir: 'up'
  }, {
    x: 8,
    y: 4,
    dir: 'up'
  }]], [["xxxxxxxxxxxxxx", "x            x", "x            x", "x          rbx", "x    x     xxx", "xb        00xx", "xx  rx  x xxxx", "xxxxxxxxxxxxxx"], [{
    x: 4,
    y: 6,
    dir: 'down'
  }]], [
  // Level 10
  ["xxxxxxxxxxxxxx", "x   gr       x", "x   00 1     x", "x    x x xxxxx", "x            x", "x  x  x      x", "x        x  rx", "xx   x     gxx", "x          xxx", "xxxxxxxxxxxxxx"], [{
    x: 11,
    y: 7,
    dir: 'down'
  }, {
    x: 12,
    y: 6,
    dir: 'down'
  }]], [["xxxxxxxxxxxxxx", "x      g00g gx", "x       xxx xx", "x           gx", "x11         xx", "xxx          x", "x       g    x", "x   x xxx   gx", "x   xxxxxx xxx", "xxxxxxxxxxxxxx"], [{
    x: 12,
    y: 7,
    dir: 'down'
  }, {
    x: 7,
    y: 1,
    dir: 'right'
  }, {
    x: 10,
    y: 1,
    dir: 'left'
  }]], [["xxxxxxxxxxxxxx", "xxr rr  rr rxx", "xxx  x  x  xxx", "x            x", "xb          bx", "xx          xx", "x            x", "x            x", "x   xxxxxx   x", "xxxxxxxxxxxxxx"], [{
    x: 12,
    y: 4,
    dir: 'down'
  }]], ["xxxxxxxxxxxxxx", "xxxxxxxxxxxxxx", "xxxxx gr xxxxx", "xxxxx rb xxxxx", "xxxxx gr xxxxx", "xxxxx bg xxxxx", "xxxxxxxxxxxxxx", "xxxxxxxxxxxxxx"], [["xxxxxxxxxxxxxx", "xxxxxxxxx   rx", "xxxxxxxxx   gx", "xxxxxxxxx   gx", "x1122       gx", "x1122       gx", "x0033      xxx", "x0033      xxx", "xxr x gxxx xxx", "xxxxxxxxxxxxxx"], [{
    x: 2,
    y: 8,
    dir: 'down'
  }, {
    x: 6,
    y: 8,
    dir: 'down'
  }]], [
  // Level 15
  ["xxxxxxxxxxxxxx", "xr r r      rx", "xg x x      gx", "xb          bx", "xxxxx     xxxx", "xxxxxx   xxxxx", "xxxxxx   xxxxx", "xxxxxx   xxxxx", "xxxxxxgggxxxxx", "xxxxxxxxxxxxxx"], [{
    x: 1,
    y: 3,
    dir: 'down'
  }, {
    x: 6,
    y: 8,
    dir: 'left'
  }, {
    x: 8,
    y: 8,
    dir: 'right'
  }]], [["xxxxxxxxxxxxxx", "xx   0001233rx", "xx   0411233xx", "xx   444122xxx", "xx     xxxxxxx", "xr     xxxxxxx", "xx     xxxxxxx", "xx     xxxxxxx", "xx     xxxxxxx", "xxxxxxxxxxxxxx"], [{
    x: 1,
    y: 5,
    dir: 'up'
  }]], [["xxxxxxxxxxxxxx", "xxxx000xxxgb x", "xxxx0     bg x", "xxxx0    11xxx", "xxxx000xxxxxxx", "x 222  xxxxxxx", "xxxx     xxgxx", "xxxx   g    bx", "xxxx   x     x", "xxxxxxxxxxxxxx"], [{
    x: 11,
    y: 6,
    dir: 'up'
  }, {
    x: 12,
    y: 7,
    dir: 'up'
  }]], [["xxxxxxxxxxxxxx", "x            x", "xb01         x", "xb0gg     g  x", "xb023     g4bx", "xxxxx g   xxxx", "xxxxx gg  xxxx", "xxxxx ggg xxxx", "xxxxx ggggxxxx", "xxxxxxxxxxxxxx"], [{
    x: 12,
    y: 4,
    dir: 'down'
  }]], [["xxxxxxxxxxxxxx", "xg0    g1gx  x", "x 3g    1 x  x", "x444    2 x  x", "xg g   ggg   x", "xxx     xxx  x", "xxx     xxx  x", "xxx     xxx  x", "xxx          x", "xxxxxxxxxxxxxx"], [{
    x: 1,
    y: 1,
    dir: 'right'
  }, {
    x: 3,
    y: 2,
    dir: 'left'
  }, {
    x: 1,
    y: 4,
    dir: 'up'
  }, {
    x: 3,
    y: 4,
    dir: 'up'
  }, {
    x: 8,
    y: 4,
    dir: 'up'
  }, {
    x: 7,
    y: 1,
    dir: 'right'
  }, {
    x: 9,
    y: 1,
    dir: 'left'
  }]], [
  // Level 20
  ["xxxxxxxxxxxxxx", "xrrrr   rggxxx", "xxxb    xxxxxx", "xxxx       xbx", "xx           x", "xx           x", "xx     x     x", "xx x         x", "xx        x  x", "xxxxxxxxxxxxxx"], [{
    x: 12,
    y: 3,
    dir: 'up'
  }]]];
  CELL_SIZE = 48;
  moveToCell = function moveToCell(dom, x, y) {
    dom.style.left = x * CELL_SIZE + 'px';
    return dom.style.top = y * CELL_SIZE + 'px';
  };
  Stage = /*#__PURE__*/function () {
    function Stage(dom1, map) {
      var _this = this;
      _classCallCheck(this, Stage);
      var anchors, event, k, len, maybeSwallowEvent, ref;
      this.dom = dom1;
      this.jellies = [];
      anchors = [];
      if (map[0] instanceof Array) {
        anchors = map[1];
        map = map[0];
      }
      this.num_monochromatic_blocks = 0;
      this.num_colors = 0;
      this.loadMap(map, anchors);
      // Capture and swallow all click events during animations.
      this.busy = false;
      maybeSwallowEvent = function maybeSwallowEvent(e) {
        e.preventDefault();
        if (_this.busy) {
          return e.stopPropagation();
        }
      };
      ref = ['contextmenu', 'click', 'touchstart', 'touchmove'];
      for (k = 0, len = ref.length; k < len; k++) {
        event = ref[k];
        this.dom.addEventListener(event, maybeSwallowEvent, true);
      }
      this.checkForMerges();
    }
    _createClass(Stage, [{
      key: "loadMap",
      value: function loadMap(map, anchors) {
        var cell, classname, color, colors, jelly, row, table, td, tr, x, y;
        table = document.createElement('table');
        this.dom.appendChild(table);
        colors = {};
        this.cells = function () {
          var k, ref, results;
          results = [];
          for (y = k = 0, ref = map.length; 0 <= ref ? k < ref : k > ref; y = 0 <= ref ? ++k : --k) {
            row = map[y].split('');
            tr = document.createElement('tr');
            table.appendChild(tr);
            results.push(function () {
              var l, ref1, results1;
              results1 = [];
              for (x = l = 0, ref1 = row.length; 0 <= ref1 ? l < ref1 : l > ref1; x = 0 <= ref1 ? ++l : --l) {
                color = null;
                classname = 'transparent';
                cell = null;
                td = document.createElement('td');
                switch (row[x]) {
                  case 'x':
                    classname = 'cell wall';
                    cell = new Wall(td);
                    break;
                  case 'r':
                    color = 'red';
                    break;
                  case 'g':
                    color = 'green';
                    break;
                  case 'b':
                    color = 'blue';
                    break;
                  case '0':
                  case '1':
                  case '2':
                  case '3':
                  case '4':
                  case '5':
                  case '6':
                  case '7':
                  case '8':
                  case '9':
                    color = 'black' + row[x];
                }
                td.className = classname;
                tr.appendChild(td);
                if (color) {
                  cell = new JellyCell(color);
                  jelly = new Jelly(this, cell, x, y);
                  this.dom.appendChild(jelly.dom);
                  this.jellies.push(jelly);
                  this.num_monochromatic_blocks += 1;
                  if (!(color in colors)) {
                    this.num_colors += 1;
                  }
                  colors[color] = 1;
                }
                results1.push(cell);
              }
              return results1;
            }.call(this));
          }
          return results;
        }.call(this);
        this.addBorders();
        this.placeAnchors(anchors);
      }
    }, {
      key: "placeAnchors",
      value: function placeAnchors(anchors) {
        var anchor, arrow, classname, colors, directions, dx, dy, jelly, k, len, me, other, property;
        directions = {
          'left': [-1, 0, 'leftarrow', 'borderRightColor'],
          'right': [1, 0, 'rightarrow', 'borderLeftColor'],
          'up': [0, -1, 'uparrow', 'borderBottomColor'],
          'down': [0, 1, 'downarrow', 'borderTopColor']
        };
        colors = {
          'red': 'hsl(0, 100%, 75%)',
          'green': 'hsl(120, 100%, 45%)',
          'blue': 'hsl(216, 100%, 70%)'
        };
        for (k = 0, len = anchors.length; k < len; k++) {
          anchor = anchors[k];
          dx = directions[anchor.dir][0];
          dy = directions[anchor.dir][1];
          classname = directions[anchor.dir][2];
          property = directions[anchor.dir][3];
          me = this.cells[anchor.y][anchor.x];
          other = this.cells[anchor.y + dy][anchor.x + dx];
          me.mergeWith(other, anchor.dir);
          // Create the overlapping anchoring triangle.
          arrow = document.createElement('div');
          arrow.style[property] = colors[me.color];
          arrow.className = classname;
          other.dom.appendChild(arrow);
        }
        return this.jellies = function () {
          var l, len1, ref, results;
          ref = this.jellies;
          results = [];
          for (l = 0, len1 = ref.length; l < len1; l++) {
            jelly = ref[l];
            if (jelly.cells) {
              results.push(jelly);
            }
          }
          return results;
        }.call(this);
      }
    }, {
      key: "addBorders",
      value: function addBorders() {
        var attr, border, cell, dx, dy, edges, k, l, len, m, other, ref, ref1, ref2, ref3, x, y;
        for (y = k = 0, ref = this.cells.length; 0 <= ref ? k < ref : k > ref; y = 0 <= ref ? ++k : --k) {
          for (x = l = 0, ref1 = this.cells[0].length; 0 <= ref1 ? l < ref1 : l > ref1; x = 0 <= ref1 ? ++l : --l) {
            cell = this.cells[y][x];
            if (!(cell instanceof Wall)) {
              continue;
            }
            border = 'solid 1px #777';
            edges = [['borderBottom', 0, 1], ['borderTop', 0, -1], ['borderLeft', -1, 0], ['borderRight', 1, 0]];
            for (m = 0, len = edges.length; m < len; m++) {
              var _edges$m = _slicedToArray(edges[m], 3);
              attr = _edges$m[0];
              dx = _edges$m[1];
              dy = _edges$m[2];
              if (!(0 <= (ref2 = y + dy) && ref2 < this.cells.length)) {
                continue;
              }
              if (!(0 <= (ref3 = x + dx) && ref3 < this.cells[0].length)) {
                continue;
              }
              other = this.cells[y + dy][x + dx];
              if (!(other instanceof Wall)) {
                cell.dom.style[attr] = border;
              }
            }
          }
        }
      }
    }, {
      key: "waitForAnimation",
      value: function waitForAnimation(cb) {
        var _this2 = this;
        var _end, k, len, name, names;
        names = ['transitionend', 'webkitTransitionEnd'];
        _end = function end() {
          var k, len, name;
          for (k = 0, len = names.length; k < len; k++) {
            name = names[k];
            _this2.dom.removeEventListener(name, _end);
          }
          // Wait one call stack before continuing.  This is necessary if there
          // are multiple pending end transition events (multiple jellies moving);
          // we want to wait for them all here and not accidentally catch them
          // in a subsequent waitForAnimation.
          return setTimeout(cb, 0);
        };
        for (k = 0, len = names.length; k < len; k++) {
          name = names[k];
          this.dom.addEventListener(name, _end);
        }
      }
    }, {
      key: "trySlide",
      value: function trySlide(jelly, dir) {
        var _this3 = this;
        var jellies;
        jellies = [jelly];
        if (this.checkFilled(jellies, dir, 0)) {
          return;
        }
        this.busy = true;
        this.move(jellies, dir, 0);
        return this.waitForAnimation(function () {
          return _this3.checkFall(function () {
            _this3.checkForMerges();
            return _this3.busy = false;
          });
        });
      }
    }, {
      key: "move",
      value: function move(jellies, dx, dy) {
        var cell, jelly, k, l, len, len1, len2, len3, len4, m, n, o, ref, ref1, x, y;
        for (k = 0, len = jellies.length; k < len; k++) {
          jelly = jellies[k];
          ref = jelly.cellCoords();
          for (l = 0, len1 = ref.length; l < len1; l++) {
            var _ref$l = _slicedToArray(ref[l], 3);
            x = _ref$l[0];
            y = _ref$l[1];
            cell = _ref$l[2];
            this.cells[y][x] = null;
          }
        }
        for (m = 0, len2 = jellies.length; m < len2; m++) {
          jelly = jellies[m];
          jelly.updatePosition(jelly.x + dx, jelly.y + dy);
        }
        for (n = 0, len3 = jellies.length; n < len3; n++) {
          jelly = jellies[n];
          ref1 = jelly.cellCoords();
          for (o = 0, len4 = ref1.length; o < len4; o++) {
            var _ref1$o = _slicedToArray(ref1[o], 3);
            x = _ref1$o[0];
            y = _ref1$o[1];
            cell = _ref1$o[2];
            this.cells[y][x] = cell;
          }
        }
      }
    }, {
      key: "checkFilled",
      value: function checkFilled(jellies, dx, dy) {
        var cell, done, jelly, k, l, len, len1, next, ref, ref1, x, y;
        done = false;
        while (!done) {
          done = true;
          for (k = 0, len = jellies.length; k < len; k++) {
            jelly = jellies[k];
            if (jelly.immovable) {
              return true;
            }
            ref = jelly.cellCoords();
            for (l = 0, len1 = ref.length; l < len1; l++) {
              var _ref$l2 = _slicedToArray(ref[l], 3);
              x = _ref$l2[0];
              y = _ref$l2[1];
              cell = _ref$l2[2];
              next = this.cells[y + dy][x + dx];
              if (!next) {
                // empty space
                continue;
              }
              if (!next.jelly) {
                // wall
                return true;
              }
              if (ref1 = next.jelly, indexOf.call(jellies, ref1) >= 0) {
                continue;
              }
              jellies.push(next.jelly);
              done = false;
              break;
            }
          }
        }
        return false;
      }
    }, {
      key: "checkFall",
      value: function checkFall(cb) {
        var jelly, jellyset, k, len, moved, ref, try_again;
        moved = false;
        try_again = true;
        while (try_again) {
          try_again = false;
          ref = this.jellies;
          for (k = 0, len = ref.length; k < len; k++) {
            jelly = ref[k];
            jellyset = [jelly];
            if (!this.checkFilled(jellyset, 0, 1)) {
              this.move(jellyset, 0, 1);
              try_again = true;
              moved = true;
            }
          }
        }
        if (moved) {
          this.waitForAnimation(cb);
        } else {
          cb();
        }
      }
    }, {
      key: "checkForMerges",
      value: function checkForMerges() {
        var merged;
        merged = false;
        while (this.doOneMerge()) {
          merged = true;
        }
        if (merged) {
          this.checkForCompletion();
        }
      }
    }, {
      key: "checkForCompletion",
      value: function checkForCompletion() {
        if (this.num_monochromatic_blocks <= this.num_colors) {
          alert("Congratulations! Level completed.");
        }
      }
    }, {
      key: "doOneMerge",
      value: function doOneMerge() {
        var cell, dir, dx, dy, jelly, k, l, len, len1, len2, m, other, ref, ref1, ref2, x, y;
        ref = this.jellies;
        for (k = 0, len = ref.length; k < len; k++) {
          jelly = ref[k];
          ref1 = jelly.cellCoords();
          for (l = 0, len1 = ref1.length; l < len1; l++) {
            var _ref1$l = _slicedToArray(ref1[l], 3);
            x = _ref1$l[0];
            y = _ref1$l[1];
            cell = _ref1$l[2];
            ref2 = [[1, 0, 'right'], [0, 1, 'down']];
            // Only look right and down; left and up are handled by that side
            // itself looking right and down.
            for (m = 0, len2 = ref2.length; m < len2; m++) {
              var _ref2$m = _slicedToArray(ref2[m], 3);
              dx = _ref2$m[0];
              dy = _ref2$m[1];
              dir = _ref2$m[2];
              other = this.cells[y + dy][x + dx];
              if (!(other && other instanceof JellyCell)) {
                continue;
              }
              if (cell['merged' + dir]) {
                continue;
              }
              if (other.color !== cell.color) {
                continue;
              }
              if (jelly !== other.jelly) {
                this.jellies = this.jellies.filter(function (j) {
                  return j !== other.jelly;
                });
              }
              if (cell.color_master !== other.color_master) {
                this.num_monochromatic_blocks -= 1;
              }
              cell.mergeWith(other, dir);
              cell['merged' + dir] = true;
              return true;
            }
          }
        }
        return false;
      }
    }]);
    return Stage;
  }();
  Wall = /*#__PURE__*/_createClass(function Wall(dom1) {
    _classCallCheck(this, Wall);
    this.dom = dom1;
  });
  JellyCell = /*#__PURE__*/function () {
    function JellyCell(color1) {
      _classCallCheck(this, JellyCell);
      this.color = color1;
      this.dom = document.createElement('div');
      this.dom.className = 'cell jelly ' + this.color;
      this.x = 0;
      this.y = 0;
      this.color_master = this;
      this.color_mates = [this];
    }
    _createClass(JellyCell, [{
      key: "mergeWith",
      value: function mergeWith(other, dir) {
        var borders, cell, corners, k, len, other_master, ref;
        borders = {
          'left': ['borderLeft', 'borderRight'],
          'right': ['borderRight', 'borderLeft'],
          'up': ['borderTop', 'borderBottom'],
          'down': ['borderBottom', 'borderTop']
        };
        corners = {
          'left': [['borderTopLeftRadius', 'borderBottomLeftRadius'], ['borderTopRightRadius', 'borderBottomRightRadius']],
          'right': [['borderTopRightRadius', 'borderBottomRightRadius'], ['borderTopLeftRadius', 'borderBottomLeftRadius']],
          'up': [['borderTopLeftRadius', 'borderTopRightRadius'], ['borderBottomLeftRadius', 'borderBottomRightRadius']],
          'down': [['borderBottomLeftRadius', 'borderBottomRightRadius'], ['borderTopLeftRadius', 'borderTopRightRadius']]
        };
        // Remove internal borders, whether merging with other jelly or wall.
        this.dom.style[borders[dir][0]] = 'none';
        other.dom.style[borders[dir][1]] = 'none';
        this.dom.style[corners[dir][0][0]] = '0';
        this.dom.style[corners[dir][0][1]] = '0';
        other.dom.style[corners[dir][1][0]] = '0';
        other.dom.style[corners[dir][1][1]] = '0';
        if (other instanceof Wall) {
          // If merging with wall, jelly becomes immovable.
          this.jelly.immovable = true;
        }
        // If merging with jelly, unify the jellies and color mates' lists.
        if (other instanceof JellyCell && this.color === other.color && this.color_master !== other.color_master) {
          other_master = other.color_master;
          ref = other_master.color_mates;
          for (k = 0, len = ref.length; k < len; k++) {
            cell = ref[k];
            cell.color_master = this.color_master;
          }
          this.color_master.color_mates = this.color_master.color_mates.concat(other_master.color_mates);
        }
        if (other instanceof JellyCell && this.jelly !== other.jelly) {
          return this.jelly.merge(other.jelly);
        }
      }
    }]);
    return JellyCell;
  }();
  Jelly = /*#__PURE__*/function () {
    function Jelly(stage, cell, x1, y1) {
      var _this4 = this;
      _classCallCheck(this, Jelly);
      this.x = x1;
      this.y = y1;
      this.dom = document.createElement('div');
      this.updatePosition(this.x, this.y);
      this.dom.className = 'cell jellybox';
      cell.jelly = this;
      this.cells = [cell];
      this.dom.appendChild(cell.dom);
      this.dom.addEventListener('contextmenu', function (e) {
        return stage.trySlide(_this4, 1);
      });
      this.dom.addEventListener('click', function (e) {
        return stage.trySlide(_this4, -1);
      });
      this.dom.addEventListener('touchstart', function (e) {
        return _this4.start = e.touches[0].pageX;
      });
      this.dom.addEventListener('touchmove', function (e) {
        var dx;
        dx = e.touches[0].pageX - _this4.start;
        if (Math.abs(dx) > 10) {
          dx = Math.max(Math.min(dx, 1), -1);
          return stage.trySlide(_this4, dx);
        }
      });
      this.immovable = false;
    }
    _createClass(Jelly, [{
      key: "cellCoords",
      value: function cellCoords() {
        var cell, k, len, ref, results;
        ref = this.cells;
        results = [];
        for (k = 0, len = ref.length; k < len; k++) {
          cell = ref[k];
          results.push([this.x + cell.x, this.y + cell.y, cell]);
        }
        return results;
      }
    }, {
      key: "updatePosition",
      value: function updatePosition(x1, y1) {
        this.x = x1;
        this.y = y1;
        return moveToCell(this.dom, this.x, this.y);
      }
    }, {
      key: "merge",
      value: function merge(other) {
        var cell, dx, dy, k, len, ref;
        // Reposition other's cells as children of this jelly.
        dx = other.x - this.x;
        dy = other.y - this.y;
        ref = other.cells;
        for (k = 0, len = ref.length; k < len; k++) {
          cell = ref[k];
          this.cells.push(cell);
          cell.x += dx;
          cell.y += dy;
          cell.jelly = this;
          moveToCell(cell.dom, cell.x, cell.y);
          this.dom.appendChild(cell.dom);
        }
        if (other.immovable) {
          this.immovable = true;
        }
        // Delete references from/to other.
        other.cells = null;
        other.dom.parentNode.removeChild(other.dom);
      }
    }]);
    return Jelly;
  }();
  level = parseInt(location.search.substr(1), 10) || 1;
  stage = new Stage(document.getElementById('map'), levels[level - 1]);
  window.stage = stage;
  levelPicker = document.getElementById('level');
  for (i = k = 1, ref = levels.length; 1 <= ref ? k <= ref : k >= ref; i = 1 <= ref ? ++k : --k) {
    option = document.createElement('option');
    option.value = i;
    option.appendChild(document.createTextNode("Level ".concat(i)));
    levelPicker.appendChild(option);
  }
  levelPicker.value = level;
  levelPicker.addEventListener('change', function () {
    return location.search = '?' + levelPicker.value;
  });
  document.getElementById('reset').addEventListener('click', function () {
    stage.dom.innerHTML = '';
    return stage = new Stage(stage.dom, levels[level - 1]);
  });
}).call(void 0);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJuYW1lcyI6WyJDRUxMX1NJWkUiLCJKZWxseSIsIkplbGx5Q2VsbCIsIlN0YWdlIiwiV2FsbCIsImkiLCJrIiwibGV2ZWwiLCJsZXZlbFBpY2tlciIsImxldmVscyIsIm1vdmVUb0NlbGwiLCJvcHRpb24iLCJyZWYiLCJzdGFnZSIsImluZGV4T2YiLCJ4IiwieSIsImRpciIsImRvbSIsInN0eWxlIiwibGVmdCIsInRvcCIsImRvbTEiLCJtYXAiLCJfdGhpcyIsIl9jbGFzc0NhbGxDaGVjayIsImFuY2hvcnMiLCJldmVudCIsImxlbiIsIm1heWJlU3dhbGxvd0V2ZW50IiwiamVsbGllcyIsIkFycmF5IiwibnVtX21vbm9jaHJvbWF0aWNfYmxvY2tzIiwibnVtX2NvbG9ycyIsImxvYWRNYXAiLCJidXN5IiwiZSIsInByZXZlbnREZWZhdWx0Iiwic3RvcFByb3BhZ2F0aW9uIiwibGVuZ3RoIiwiYWRkRXZlbnRMaXN0ZW5lciIsImNoZWNrRm9yTWVyZ2VzIiwiX2NyZWF0ZUNsYXNzIiwia2V5IiwidmFsdWUiLCJjZWxsIiwiY2xhc3NuYW1lIiwiY29sb3IiLCJjb2xvcnMiLCJqZWxseSIsInJvdyIsInRhYmxlIiwidGQiLCJ0ciIsImRvY3VtZW50IiwiY3JlYXRlRWxlbWVudCIsImFwcGVuZENoaWxkIiwiY2VsbHMiLCJyZXN1bHRzIiwic3BsaXQiLCJyZXN1bHRzMSIsImwiLCJyZWYxIiwiY2xhc3NOYW1lIiwicHVzaCIsImFkZEJvcmRlcnMiLCJwbGFjZUFuY2hvcnMiLCJhbmNob3IiLCJhcnJvdyIsImRpcmVjdGlvbnMiLCJkeCIsImR5IiwibWUiLCJvdGhlciIsInByb3BlcnR5IiwibWVyZ2VXaXRoIiwibGVuMSIsImF0dHIiLCJib3JkZXIiLCJlZGdlcyIsIm0iLCJyZWYyIiwicmVmMyIsIl9lZGdlcyRtIiwiX3NsaWNlZFRvQXJyYXkiLCJ3YWl0Rm9yQW5pbWF0aW9uIiwiY2IiLCJfdGhpczIiLCJlbmQiLCJuYW1lIiwibmFtZXMiLCJyZW1vdmVFdmVudExpc3RlbmVyIiwic2V0VGltZW91dCIsInRyeVNsaWRlIiwiX3RoaXMzIiwiY2hlY2tGaWxsZWQiLCJtb3ZlIiwiY2hlY2tGYWxsIiwibGVuMiIsImxlbjMiLCJsZW40IiwibiIsIm8iLCJjZWxsQ29vcmRzIiwiX3JlZiRsIiwidXBkYXRlUG9zaXRpb24iLCJfcmVmMSRvIiwiZG9uZSIsIm5leHQiLCJpbW1vdmFibGUiLCJfcmVmJGwyIiwiY2FsbCIsImplbGx5c2V0IiwibW92ZWQiLCJ0cnlfYWdhaW4iLCJtZXJnZWQiLCJkb09uZU1lcmdlIiwiY2hlY2tGb3JDb21wbGV0aW9uIiwiYWxlcnQiLCJfcmVmMSRsIiwiX3JlZjIkbSIsImZpbHRlciIsImoiLCJjb2xvcl9tYXN0ZXIiLCJjb2xvcjEiLCJjb2xvcl9tYXRlcyIsImJvcmRlcnMiLCJjb3JuZXJzIiwib3RoZXJfbWFzdGVyIiwiY29uY2F0IiwibWVyZ2UiLCJ4MSIsInkxIiwiX3RoaXM0Iiwic3RhcnQiLCJ0b3VjaGVzIiwicGFnZVgiLCJNYXRoIiwiYWJzIiwibWF4IiwibWluIiwicGFyZW50Tm9kZSIsInJlbW92ZUNoaWxkIiwicGFyc2VJbnQiLCJsb2NhdGlvbiIsInNlYXJjaCIsInN1YnN0ciIsImdldEVsZW1lbnRCeUlkIiwid2luZG93IiwiY3JlYXRlVGV4dE5vZGUiLCJpbm5lckhUTUwiXSwic291cmNlcyI6WyJcXC9qZWxseS5jb2ZmZWUiXSwic291cmNlc0NvbnRlbnQiOlsibGV2ZWxzID0gW1xyXG4gICMgTGV2ZWwgMVxyXG4gIFsgXCJ4eHh4eHh4eHh4eHh4eFwiLFxyXG4gICAgXCJ4ICAgICAgICAgICAgeFwiLFxyXG4gICAgXCJ4ICAgICAgICAgICAgeFwiLFxyXG4gICAgXCJ4ICAgICAgciAgICAgeFwiLFxyXG4gICAgXCJ4ICAgICAgeHggICAgeFwiLFxyXG4gICAgXCJ4ICBnICAgICByIGIgeFwiLFxyXG4gICAgXCJ4eGJ4eHhnIHh4eHh4eFwiLFxyXG4gICAgXCJ4eHh4eHh4eHh4eHh4eFwiLCBdLFxyXG5cclxuICBbIFwieHh4eHh4eHh4eHh4eHhcIixcclxuICAgIFwieCAgICAgICAgICAgIHhcIixcclxuICAgIFwieCAgICAgICAgICAgIHhcIixcclxuICAgIFwieCAgICAgICAgICAgIHhcIixcclxuICAgIFwieCAgICAgZyAgIGcgIHhcIixcclxuICAgIFwieCAgIHIgciAgIHIgIHhcIixcclxuICAgIFwieHh4eHggeCB4IHh4eHhcIixcclxuICAgIFwieHh4eHh4eHh4eHh4eHhcIiwgXSxcclxuXHJcbiAgWyBcInh4eHh4eHh4eHh4eHh4XCIsXHJcbiAgICBcInggICAgICAgICAgICB4XCIsXHJcbiAgICBcInggICAgICAgICAgICB4XCIsXHJcbiAgICBcInggICBiZyAgeCBnICB4XCIsXHJcbiAgICBcInh4eCB4eHhyeHh4ICB4XCIsXHJcbiAgICBcInggICAgICBiICAgICB4XCIsXHJcbiAgICBcInh4eCB4eHhyeHh4eHh4XCIsXHJcbiAgICBcInh4eHh4eHh4eHh4eHh4XCIsIF0sXHJcblxyXG4gIFsgXCJ4eHh4eHh4eHh4eHh4eFwiLFxyXG4gICAgXCJ4ICAgICAgICAgICAgeFwiLFxyXG4gICAgXCJ4ICAgICAgIHIgICAgeFwiLFxyXG4gICAgXCJ4ICAgICAgIGIgICAgeFwiLFxyXG4gICAgXCJ4ICAgICAgIHggICAgeFwiLFxyXG4gICAgXCJ4IGIgciAgICAgICAgeFwiLFxyXG4gICAgXCJ4IGIgciAgICAgIGIgeFwiLFxyXG4gICAgXCJ4eHggeCAgICAgIHh4eFwiLFxyXG4gICAgXCJ4eHh4eCB4eHh4eHh4eFwiLFxyXG4gICAgXCJ4eHh4eHh4eHh4eHh4eFwiLCBdLFxyXG5cclxuICAjIExldmVsIDVcclxuICBbIFwieHh4eHh4eHh4eHh4eHhcIixcclxuICAgIFwieCAgICAgICAgICAgIHhcIixcclxuICAgIFwieCAgICAgICAgICAgIHhcIixcclxuICAgIFwieHJnICBnZyAgICAgIHhcIixcclxuICAgIFwieHh4IHh4eHggeHggIHhcIixcclxuICAgIFwieHJnICAgICAgICAgIHhcIixcclxuICAgIFwieHh4eHggIHh4ICAgeHhcIixcclxuICAgIFwieHh4eHh4IHh4ICB4eHhcIixcclxuICAgIFwieHh4eHh4eHh4eHh4eHhcIiwgXSxcclxuXHJcbiAgWyBcInh4eHh4eHh4eHh4eHh4XCIsXHJcbiAgICBcInh4eHh4eHggICAgICB4XCIsXHJcbiAgICBcInh4eHh4eHggZyAgICB4XCIsXHJcbiAgICBcInggICAgICAgeHggICB4XCIsXHJcbiAgICBcInggciAgIGIgICAgICB4XCIsXHJcbiAgICBcInggeCB4eHggeCBnICB4XCIsXHJcbiAgICBcInggICAgICAgICB4IGJ4XCIsXHJcbiAgICBcInggICAgICAgciB4eHh4XCIsXHJcbiAgICBcInggICB4eHh4eHh4eHh4XCIsXHJcbiAgICBcInh4eHh4eHh4eHh4eHh4XCIsIF0sXHJcblxyXG4gICMgQW5jaG9yZWQgamVsbGllcyBhcmUgc3BlY2lmaWVkIHNlcGFyYXRlbHkgYWZ0ZXIgdGhlXHJcbiAgIyBsZXZlbCBtYXAuIEluc3RlYWQgb2YgW3Jvdywgcm93LCByb3cuLi5pbiB0aGUgcHJlc2VuY2Ugb2ZcclxuICAjIGFuY2hvcnMgdGhlIGxldmVsIHNwZWNpZmljYXRpb24gaXM6XHJcbiAgIyBbIFtyb3cscm93LHJvdy4uLl0sIFsgYW5jaG9yLCBhbmNob3IsIGFuY2hvci4uLl0gXS5cclxuICAjIEVhY2ggYW5jaG9yIHN0YXJ0cyBmcm9tIGEgY29sb3JlZCBub24tYmxhY2sgamVsbHknc1xyXG4gICMgY29vcmRpbmF0ZXMgYW5kIHNwZWNpZmllcyB0aGUgZGlyZWN0aW9uIGluIHdoaWNoIGl0J3MgXCJoZWxkXCIuXHJcbiAgWyBbIFwieHh4eHh4eHh4eHh4eHhcIixcclxuICAgICAgXCJ4ICAgICAgICAgICAgeFwiLFxyXG4gICAgICBcInggICAgICAgICAgciB4XCIsXHJcbiAgICAgIFwieCAgICAgICAgICB4IHhcIixcclxuICAgICAgXCJ4ICAgICBiICAgYiAgeFwiLFxyXG4gICAgICBcInggICAgIHggIHJyICB4XCIsXHJcbiAgICAgIFwieCAgICAgICAgIHggIHhcIixcclxuICAgICAgXCJ4IHIgIGJ4IHggeCAgeFwiLFxyXG4gICAgICBcInggeCAgeHggeCB4ICB4XCIsXHJcbiAgICAgIFwieHh4eHh4eHh4eHh4eHhcIiwgXSxcclxuICAgIFtcclxuICAgICAgeyB4OjIsIHk6NywgZGlyOidkb3duJyB9LFxyXG4gICAgICB7IHg6NSwgeTo3LCBkaXI6J2Rvd24nIH0sXHJcbiAgICBdXHJcbiAgXSxcclxuXHJcbiAgWyBbIFwieHh4eHh4eHh4eHh4eHhcIixcclxuICAgICAgXCJ4eHh4IHggIHggeHh4eFwiLFxyXG4gICAgICBcInh4eCAgZyAgYiAgeHh4XCIsXHJcbiAgICAgIFwieHggICB4ICB4ICAgeHhcIixcclxuICAgICAgXCJ4eCAgIGIgIGcgICB4eFwiLFxyXG4gICAgICBcInh4ZyAgICAgICAgYnh4XCIsXHJcbiAgICAgIFwieHh4ZyAgICAgIGJ4eHhcIixcclxuICAgICAgXCJ4eHh4ICAgICAgeHh4eFwiLFxyXG4gICAgICBcInh4eHh4eHh4eHh4eHh4XCIsIF0sXHJcbiAgICBbXHJcbiAgICAgIHsgeDo1LCB5OjQsIGRpcjondXAnIH0sXHJcbiAgICAgIHsgeDo4LCB5OjQsIGRpcjondXAnIH0sXHJcbiAgICBdXHJcbiAgXSxcclxuXHJcbiAgWyBbIFwieHh4eHh4eHh4eHh4eHhcIixcclxuICAgICAgXCJ4ICAgICAgICAgICAgeFwiLFxyXG4gICAgICBcInggICAgICAgICAgICB4XCIsXHJcbiAgICAgIFwieCAgICAgICAgICByYnhcIixcclxuICAgICAgXCJ4ICAgIHggICAgIHh4eFwiLFxyXG4gICAgICBcInhiICAgICAgICAwMHh4XCIsXHJcbiAgICAgIFwieHggIHJ4ICB4IHh4eHhcIixcclxuICAgICAgXCJ4eHh4eHh4eHh4eHh4eFwiLCBdLFxyXG4gICAgW1xyXG4gICAgICB7IHg6NCwgeTo2LCBkaXI6J2Rvd24nIH0sXHJcbiAgICBdLFxyXG4gIF0sXHJcblxyXG4gICMgTGV2ZWwgMTBcclxuICBbIFsgXCJ4eHh4eHh4eHh4eHh4eFwiLFxyXG4gICAgICBcInggICBnciAgICAgICB4XCIsXHJcbiAgICAgIFwieCAgIDAwIDEgICAgIHhcIixcclxuICAgICAgXCJ4ICAgIHggeCB4eHh4eFwiLFxyXG4gICAgICBcInggICAgICAgICAgICB4XCIsXHJcbiAgICAgIFwieCAgeCAgeCAgICAgIHhcIixcclxuICAgICAgXCJ4ICAgICAgICB4ICByeFwiLFxyXG4gICAgICBcInh4ICAgeCAgICAgZ3h4XCIsXHJcbiAgICAgIFwieCAgICAgICAgICB4eHhcIixcclxuICAgICAgXCJ4eHh4eHh4eHh4eHh4eFwiLCBdLFxyXG4gICAgW1xyXG4gICAgICB7IHg6MTEsIHk6NywgZGlyOidkb3duJyB9LFxyXG4gICAgICB7IHg6MTIsIHk6NiwgZGlyOidkb3duJyB9LFxyXG4gICAgXSxcclxuICBdLFxyXG5cclxuICBbIFsgXCJ4eHh4eHh4eHh4eHh4eFwiLFxyXG4gICAgICBcInggICAgICBnMDBnIGd4XCIsXHJcbiAgICAgIFwieCAgICAgICB4eHggeHhcIixcclxuICAgICAgXCJ4ICAgICAgICAgICBneFwiLFxyXG4gICAgICBcIngxMSAgICAgICAgIHh4XCIsXHJcbiAgICAgIFwieHh4ICAgICAgICAgIHhcIixcclxuICAgICAgXCJ4ICAgICAgIGcgICAgeFwiLFxyXG4gICAgICBcInggICB4IHh4eCAgIGd4XCIsXHJcbiAgICAgIFwieCAgIHh4eHh4eCB4eHhcIixcclxuICAgICAgXCJ4eHh4eHh4eHh4eHh4eFwiLCBdLFxyXG4gICAgW1xyXG4gICAgICB7IHg6MTIsIHk6NywgZGlyOidkb3duJyB9LFxyXG4gICAgICB7IHg6NywgeToxLCBkaXI6J3JpZ2h0JyB9LFxyXG4gICAgICB7IHg6MTAsIHk6MSwgZGlyOidsZWZ0JyB9LFxyXG4gICAgXSxcclxuICBdLFxyXG5cclxuICBbIFsgXCJ4eHh4eHh4eHh4eHh4eFwiLFxyXG4gICAgICBcInh4ciByciAgcnIgcnh4XCIsXHJcbiAgICAgIFwieHh4ICB4ICB4ICB4eHhcIixcclxuICAgICAgXCJ4ICAgICAgICAgICAgeFwiLFxyXG4gICAgICBcInhiICAgICAgICAgIGJ4XCIsXHJcbiAgICAgIFwieHggICAgICAgICAgeHhcIixcclxuICAgICAgXCJ4ICAgICAgICAgICAgeFwiLFxyXG4gICAgICBcInggICAgICAgICAgICB4XCIsXHJcbiAgICAgIFwieCAgIHh4eHh4eCAgIHhcIixcclxuICAgICAgXCJ4eHh4eHh4eHh4eHh4eFwiLCBdLFxyXG4gICAgW1xyXG4gICAgICB7IHg6MTIsIHk6NCwgZGlyOidkb3duJyB9LFxyXG4gICAgXSxcclxuICBdLFxyXG5cclxuICBbIFwieHh4eHh4eHh4eHh4eHhcIixcclxuICAgIFwieHh4eHh4eHh4eHh4eHhcIixcclxuICAgIFwieHh4eHggZ3IgeHh4eHhcIixcclxuICAgIFwieHh4eHggcmIgeHh4eHhcIixcclxuICAgIFwieHh4eHggZ3IgeHh4eHhcIixcclxuICAgIFwieHh4eHggYmcgeHh4eHhcIixcclxuICAgIFwieHh4eHh4eHh4eHh4eHhcIixcclxuICAgIFwieHh4eHh4eHh4eHh4eHhcIiwgXSxcclxuXHJcbiAgWyBbIFwieHh4eHh4eHh4eHh4eHhcIixcclxuICAgICAgXCJ4eHh4eHh4eHggICByeFwiLFxyXG4gICAgICBcInh4eHh4eHh4eCAgIGd4XCIsXHJcbiAgICAgIFwieHh4eHh4eHh4ICAgZ3hcIixcclxuICAgICAgXCJ4MTEyMiAgICAgICBneFwiLFxyXG4gICAgICBcIngxMTIyICAgICAgIGd4XCIsXHJcbiAgICAgIFwieDAwMzMgICAgICB4eHhcIixcclxuICAgICAgXCJ4MDAzMyAgICAgIHh4eFwiLFxyXG4gICAgICBcInh4ciB4IGd4eHggeHh4XCIsXHJcbiAgICAgIFwieHh4eHh4eHh4eHh4eHhcIiwgXSxcclxuICAgIFtcclxuICAgICAgeyB4OjIsIHk6OCwgZGlyOidkb3duJyB9LFxyXG4gICAgICB7IHg6NiwgeTo4LCBkaXI6J2Rvd24nIH0sXHJcbiAgICBdLFxyXG4gIF0sXHJcblxyXG4gICMgTGV2ZWwgMTVcclxuICBbIFsgXCJ4eHh4eHh4eHh4eHh4eFwiLFxyXG4gICAgICBcInhyIHIgciAgICAgIHJ4XCIsXHJcbiAgICAgIFwieGcgeCB4ICAgICAgZ3hcIixcclxuICAgICAgXCJ4YiAgICAgICAgICBieFwiLFxyXG4gICAgICBcInh4eHh4ICAgICB4eHh4XCIsXHJcbiAgICAgIFwieHh4eHh4ICAgeHh4eHhcIixcclxuICAgICAgXCJ4eHh4eHggICB4eHh4eFwiLFxyXG4gICAgICBcInh4eHh4eCAgIHh4eHh4XCIsXHJcbiAgICAgIFwieHh4eHh4Z2dneHh4eHhcIixcclxuICAgICAgXCJ4eHh4eHh4eHh4eHh4eFwiLCBdLFxyXG4gICAgW1xyXG4gICAgICB7IHg6MSwgeTozLCBkaXI6J2Rvd24nIH0sXHJcbiAgICAgIHsgeDo2LCB5OjgsIGRpcjonbGVmdCcgfSxcclxuICAgICAgeyB4OjgsIHk6OCwgZGlyOidyaWdodCcgfSxcclxuICAgIF0sXHJcbiAgXSxcclxuXHJcbiAgWyBbIFwieHh4eHh4eHh4eHh4eHhcIixcclxuICAgICAgXCJ4eCAgIDAwMDEyMzNyeFwiLFxyXG4gICAgICBcInh4ICAgMDQxMTIzM3h4XCIsXHJcbiAgICAgIFwieHggICA0NDQxMjJ4eHhcIixcclxuICAgICAgXCJ4eCAgICAgeHh4eHh4eFwiLFxyXG4gICAgICBcInhyICAgICB4eHh4eHh4XCIsXHJcbiAgICAgIFwieHggICAgIHh4eHh4eHhcIixcclxuICAgICAgXCJ4eCAgICAgeHh4eHh4eFwiLFxyXG4gICAgICBcInh4ICAgICB4eHh4eHh4XCIsXHJcbiAgICAgIFwieHh4eHh4eHh4eHh4eHhcIiwgXSxcclxuICAgIFtcclxuICAgICAgeyB4OjEsIHk6NSwgZGlyOid1cCcgfSxcclxuICAgIF0sXHJcbiAgXSxcclxuXHJcbiAgWyBbIFwieHh4eHh4eHh4eHh4eHhcIixcclxuICAgICAgXCJ4eHh4MDAweHh4Z2IgeFwiLFxyXG4gICAgICBcInh4eHgwICAgICBiZyB4XCIsXHJcbiAgICAgIFwieHh4eDAgICAgMTF4eHhcIixcclxuICAgICAgXCJ4eHh4MDAweHh4eHh4eFwiLFxyXG4gICAgICBcInggMjIyICB4eHh4eHh4XCIsXHJcbiAgICAgIFwieHh4eCAgICAgeHhneHhcIixcclxuICAgICAgXCJ4eHh4ICAgZyAgICBieFwiLFxyXG4gICAgICBcInh4eHggICB4ICAgICB4XCIsXHJcbiAgICAgIFwieHh4eHh4eHh4eHh4eHhcIiwgXSxcclxuICAgIFtcclxuICAgICAgeyB4OjExLCB5OjYsIGRpcjondXAnIH0sXHJcbiAgICAgIHsgeDoxMiwgeTo3LCBkaXI6J3VwJyB9LFxyXG4gICAgXSxcclxuICBdLFxyXG5cclxuICBbIFsgXCJ4eHh4eHh4eHh4eHh4eFwiLFxyXG4gICAgICBcInggICAgICAgICAgICB4XCIsXHJcbiAgICAgIFwieGIwMSAgICAgICAgIHhcIixcclxuICAgICAgXCJ4YjBnZyAgICAgZyAgeFwiLFxyXG4gICAgICBcInhiMDIzICAgICBnNGJ4XCIsXHJcbiAgICAgIFwieHh4eHggZyAgIHh4eHhcIixcclxuICAgICAgXCJ4eHh4eCBnZyAgeHh4eFwiLFxyXG4gICAgICBcInh4eHh4IGdnZyB4eHh4XCIsXHJcbiAgICAgIFwieHh4eHggZ2dnZ3h4eHhcIixcclxuICAgICAgXCJ4eHh4eHh4eHh4eHh4eFwiLCBdLFxyXG4gICAgW1xyXG4gICAgICB7IHg6MTIsIHk6NCwgZGlyOidkb3duJyB9LFxyXG4gICAgXSxcclxuICBdLFxyXG5cclxuICBbIFsgXCJ4eHh4eHh4eHh4eHh4eFwiLFxyXG4gICAgICBcInhnMCAgICBnMWd4ICB4XCIsXHJcbiAgICAgIFwieCAzZyAgICAxIHggIHhcIixcclxuICAgICAgXCJ4NDQ0ICAgIDIgeCAgeFwiLFxyXG4gICAgICBcInhnIGcgICBnZ2cgICB4XCIsXHJcbiAgICAgIFwieHh4ICAgICB4eHggIHhcIixcclxuICAgICAgXCJ4eHggICAgIHh4eCAgeFwiLFxyXG4gICAgICBcInh4eCAgICAgeHh4ICB4XCIsXHJcbiAgICAgIFwieHh4ICAgICAgICAgIHhcIixcclxuICAgICAgXCJ4eHh4eHh4eHh4eHh4eFwiLCBdLFxyXG4gICAgW1xyXG4gICAgICB7IHg6MSwgeToxLCBkaXI6J3JpZ2h0JyB9LFxyXG4gICAgICB7IHg6MywgeToyLCBkaXI6J2xlZnQnIH0sXHJcbiAgICAgIHsgeDoxLCB5OjQsIGRpcjondXAnIH0sXHJcbiAgICAgIHsgeDozLCB5OjQsIGRpcjondXAnIH0sXHJcbiAgICAgIHsgeDo4LCB5OjQsIGRpcjondXAnIH0sXHJcbiAgICAgIHsgeDo3LCB5OjEsIGRpcjoncmlnaHQnIH0sXHJcbiAgICAgIHsgeDo5LCB5OjEsIGRpcjonbGVmdCcgfSxcclxuICAgIF0sXHJcbiAgXSxcclxuXHJcbiAgIyBMZXZlbCAyMFxyXG4gIFsgWyBcInh4eHh4eHh4eHh4eHh4XCIsXHJcbiAgICAgIFwieHJycnIgICByZ2d4eHhcIixcclxuICAgICAgXCJ4eHhiICAgIHh4eHh4eFwiLFxyXG4gICAgICBcInh4eHggICAgICAgeGJ4XCIsXHJcbiAgICAgIFwieHggICAgICAgICAgIHhcIixcclxuICAgICAgXCJ4eCAgICAgICAgICAgeFwiLFxyXG4gICAgICBcInh4ICAgICB4ICAgICB4XCIsXHJcbiAgICAgIFwieHggeCAgICAgICAgIHhcIixcclxuICAgICAgXCJ4eCAgICAgICAgeCAgeFwiLFxyXG4gICAgICBcInh4eHh4eHh4eHh4eHh4XCIsIF0sXHJcbiAgICBbXHJcbiAgICAgIHsgeDoxMiwgeTozLCBkaXI6J3VwJyB9LFxyXG4gICAgXSxcclxuICBdLFxyXG5cclxuICBdXHJcblxyXG5DRUxMX1NJWkUgPSA0OFxyXG5cclxubW92ZVRvQ2VsbCA9IChkb20sIHgsIHkpIC0+XHJcbiAgZG9tLnN0eWxlLmxlZnQgPSB4ICogQ0VMTF9TSVpFICsgJ3B4J1xyXG4gIGRvbS5zdHlsZS50b3AgPSB5ICogQ0VMTF9TSVpFICsgJ3B4J1xyXG5cclxuY2xhc3MgU3RhZ2VcclxuICBjb25zdHJ1Y3RvcjogKEBkb20sIG1hcCkgLT5cclxuICAgIEBqZWxsaWVzID0gW11cclxuICAgIGFuY2hvcnMgPSBbXVxyXG4gICAgaWYgbWFwWzBdIGluc3RhbmNlb2YgQXJyYXlcclxuICAgICAgYW5jaG9ycyA9IG1hcFsxXVxyXG4gICAgICBtYXAgPSBtYXBbMF1cclxuICAgIEBudW1fbW9ub2Nocm9tYXRpY19ibG9ja3MgPSAwXHJcbiAgICBAbnVtX2NvbG9ycyA9IDBcclxuICAgIEBsb2FkTWFwKG1hcCwgYW5jaG9ycylcclxuXHJcbiAgICAjIENhcHR1cmUgYW5kIHN3YWxsb3cgYWxsIGNsaWNrIGV2ZW50cyBkdXJpbmcgYW5pbWF0aW9ucy5cclxuICAgIEBidXN5ID0gZmFsc2VcclxuICAgIG1heWJlU3dhbGxvd0V2ZW50ID0gKGUpID0+XHJcbiAgICAgIGUucHJldmVudERlZmF1bHQoKVxyXG4gICAgICBlLnN0b3BQcm9wYWdhdGlvbigpIGlmIEBidXN5XHJcbiAgICBmb3IgZXZlbnQgaW4gWydjb250ZXh0bWVudScsICdjbGljaycsICd0b3VjaHN0YXJ0JywgJ3RvdWNobW92ZSddXHJcbiAgICAgIEBkb20uYWRkRXZlbnRMaXN0ZW5lcihldmVudCwgbWF5YmVTd2FsbG93RXZlbnQsIHRydWUpXHJcblxyXG4gICAgQGNoZWNrRm9yTWVyZ2VzKClcclxuXHJcbiAgbG9hZE1hcDogKG1hcCwgYW5jaG9ycykgLT5cclxuICAgIHRhYmxlID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgndGFibGUnKVxyXG4gICAgQGRvbS5hcHBlbmRDaGlsZCh0YWJsZSlcclxuICAgIGNvbG9ycyA9IHt9XHJcbiAgICBAY2VsbHMgPSBmb3IgeSBpbiBbMC4uLm1hcC5sZW5ndGhdXHJcbiAgICAgIHJvdyA9IG1hcFt5XS5zcGxpdCgnJylcclxuICAgICAgdHIgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCd0cicpXHJcbiAgICAgIHRhYmxlLmFwcGVuZENoaWxkKHRyKVxyXG4gICAgICBmb3IgeCBpbiBbMC4uLnJvdy5sZW5ndGhdXHJcbiAgICAgICAgY29sb3IgPSBudWxsXHJcbiAgICAgICAgY2xhc3NuYW1lID0gJ3RyYW5zcGFyZW50J1xyXG4gICAgICAgIGNlbGwgPSBudWxsXHJcbiAgICAgICAgdGQgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCd0ZCcpXHJcbiAgICAgICAgc3dpdGNoIHJvd1t4XVxyXG4gICAgICAgICAgd2hlbiAneCdcclxuICAgICAgICAgICAgY2xhc3NuYW1lID0gJ2NlbGwgd2FsbCdcclxuICAgICAgICAgICAgY2VsbCA9IG5ldyBXYWxsKHRkKVxyXG4gICAgICAgICAgd2hlbiAncicgdGhlbiBjb2xvciA9ICdyZWQnXHJcbiAgICAgICAgICB3aGVuICdnJyB0aGVuIGNvbG9yID0gJ2dyZWVuJ1xyXG4gICAgICAgICAgd2hlbiAnYicgdGhlbiBjb2xvciA9ICdibHVlJ1xyXG4gICAgICAgICAgd2hlbiAnMCcsJzEnLCcyJywnMycsJzQnLCc1JywnNicsJzcnLCc4JywnOSdcclxuICAgICAgICAgICAgY29sb3IgPSAnYmxhY2snICsgcm93W3hdXHJcbiAgICAgICAgdGQuY2xhc3NOYW1lID0gY2xhc3NuYW1lXHJcbiAgICAgICAgdHIuYXBwZW5kQ2hpbGQodGQpXHJcbiAgICAgICAgaWYgY29sb3JcclxuICAgICAgICAgIGNlbGwgPSBuZXcgSmVsbHlDZWxsKGNvbG9yKVxyXG4gICAgICAgICAgamVsbHkgPSBuZXcgSmVsbHkodGhpcywgY2VsbCwgeCwgeSlcclxuICAgICAgICAgIEBkb20uYXBwZW5kQ2hpbGQoamVsbHkuZG9tKVxyXG4gICAgICAgICAgQGplbGxpZXMucHVzaCBqZWxseVxyXG4gICAgICAgICAgQG51bV9tb25vY2hyb21hdGljX2Jsb2NrcyArPSAxO1xyXG4gICAgICAgICAgQG51bV9jb2xvcnMgKz0xIHVubGVzcyBjb2xvciBvZiBjb2xvcnNcclxuICAgICAgICAgIGNvbG9yc1tjb2xvcl0gPSAxXHJcbiAgICAgICAgY2VsbFxyXG4gICAgQGFkZEJvcmRlcnMoKVxyXG4gICAgQHBsYWNlQW5jaG9ycyhhbmNob3JzKVxyXG4gICAgcmV0dXJuXHJcblxyXG4gIHBsYWNlQW5jaG9yczogKGFuY2hvcnMpIC0+XHJcbiAgICBkaXJlY3Rpb25zID0ge1xyXG4gICAgICAnbGVmdCc6ICBbLTEsICAwLCAnbGVmdGFycm93JywgJ2JvcmRlclJpZ2h0Q29sb3InXSxcclxuICAgICAgJ3JpZ2h0JzogWyAxLCAgMCwgJ3JpZ2h0YXJyb3cnLCAnYm9yZGVyTGVmdENvbG9yJ10sXHJcbiAgICAgICd1cCc6ICAgIFsgMCwgLTEsICd1cGFycm93JywgJ2JvcmRlckJvdHRvbUNvbG9yJ10sXHJcbiAgICAgICdkb3duJzogIFsgMCwgIDEsICdkb3duYXJyb3cnLCAnYm9yZGVyVG9wQ29sb3InXSxcclxuICAgIH1cclxuICAgIGNvbG9ycyA9IHtcclxuICAgICAgJ3JlZCcgIDogJ2hzbCgwLCAxMDAlLCA3NSUpJ1xyXG4gICAgICAnZ3JlZW4nOiAnaHNsKDEyMCwgMTAwJSwgNDUlKSdcclxuICAgICAgJ2JsdWUnIDogJ2hzbCgyMTYsIDEwMCUsIDcwJSknXHJcbiAgICB9XHJcbiAgICBmb3IgYW5jaG9yIGluIGFuY2hvcnNcclxuICAgICAgZHggPSBkaXJlY3Rpb25zW2FuY2hvci5kaXJdWzBdXHJcbiAgICAgIGR5ID0gZGlyZWN0aW9uc1thbmNob3IuZGlyXVsxXVxyXG4gICAgICBjbGFzc25hbWUgPSBkaXJlY3Rpb25zW2FuY2hvci5kaXJdWzJdXHJcbiAgICAgIHByb3BlcnR5ID0gZGlyZWN0aW9uc1thbmNob3IuZGlyXVszXVxyXG5cclxuICAgICAgbWUgPSBAY2VsbHNbYW5jaG9yLnldW2FuY2hvci54XVxyXG4gICAgICBvdGhlciA9IEBjZWxsc1thbmNob3IueSArIGR5XVthbmNob3IueCArIGR4XVxyXG4gICAgICBtZS5tZXJnZVdpdGgob3RoZXIsIGFuY2hvci5kaXIpXHJcblxyXG4gICAgICAjIENyZWF0ZSB0aGUgb3ZlcmxhcHBpbmcgYW5jaG9yaW5nIHRyaWFuZ2xlLlxyXG4gICAgICBhcnJvdyA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2RpdicpXHJcbiAgICAgIGFycm93LnN0eWxlW3Byb3BlcnR5XSA9IGNvbG9yc1ttZS5jb2xvcl1cclxuICAgICAgYXJyb3cuY2xhc3NOYW1lID0gY2xhc3NuYW1lXHJcbiAgICAgIG90aGVyLmRvbS5hcHBlbmRDaGlsZChhcnJvdylcclxuICAgIEBqZWxsaWVzID0gKGplbGx5IGZvciBqZWxseSBpbiBAamVsbGllcyB3aGVuIGplbGx5LmNlbGxzKVxyXG5cclxuICBhZGRCb3JkZXJzOiAtPlxyXG4gICAgZm9yIHkgaW4gWzAuLi5AY2VsbHMubGVuZ3RoXVxyXG4gICAgICBmb3IgeCBpbiBbMC4uLkBjZWxsc1swXS5sZW5ndGhdXHJcbiAgICAgICAgY2VsbCA9IEBjZWxsc1t5XVt4XVxyXG4gICAgICAgIGNvbnRpbnVlIHVubGVzcyBjZWxsIGluc3RhbmNlb2YgV2FsbFxyXG4gICAgICAgIGJvcmRlciA9ICdzb2xpZCAxcHggIzc3NydcclxuICAgICAgICBlZGdlcyA9IFtcclxuICAgICAgICAgIFsnYm9yZGVyQm90dG9tJywgIDAsICAxXSxcclxuICAgICAgICAgIFsnYm9yZGVyVG9wJywgICAgIDAsIC0xXSxcclxuICAgICAgICAgIFsnYm9yZGVyTGVmdCcsICAgLTEsICAwXSxcclxuICAgICAgICAgIFsnYm9yZGVyUmlnaHQnLCAgIDEsICAwXSxcclxuICAgICAgICBdXHJcbiAgICAgICAgZm9yIFthdHRyLCBkeCwgZHldIGluIGVkZ2VzXHJcbiAgICAgICAgICBjb250aW51ZSB1bmxlc3MgMCA8PSAoeStkeSkgPCBAY2VsbHMubGVuZ3RoXHJcbiAgICAgICAgICBjb250aW51ZSB1bmxlc3MgMCA8PSAoeCtkeCkgPCBAY2VsbHNbMF0ubGVuZ3RoXHJcbiAgICAgICAgICBvdGhlciA9IEBjZWxsc1t5K2R5XVt4K2R4XVxyXG4gICAgICAgICAgY2VsbC5kb20uc3R5bGVbYXR0cl0gPSBib3JkZXIgdW5sZXNzIG90aGVyIGluc3RhbmNlb2YgV2FsbFxyXG4gICAgcmV0dXJuXHJcblxyXG4gIHdhaXRGb3JBbmltYXRpb246IChjYikgLT5cclxuICAgIG5hbWVzID0gWyd0cmFuc2l0aW9uZW5kJywgJ3dlYmtpdFRyYW5zaXRpb25FbmQnXVxyXG4gICAgZW5kID0gKCkgPT5cclxuICAgICAgQGRvbS5yZW1vdmVFdmVudExpc3RlbmVyKG5hbWUsIGVuZCkgZm9yIG5hbWUgaW4gbmFtZXNcclxuICAgICAgIyBXYWl0IG9uZSBjYWxsIHN0YWNrIGJlZm9yZSBjb250aW51aW5nLiAgVGhpcyBpcyBuZWNlc3NhcnkgaWYgdGhlcmVcclxuICAgICAgIyBhcmUgbXVsdGlwbGUgcGVuZGluZyBlbmQgdHJhbnNpdGlvbiBldmVudHMgKG11bHRpcGxlIGplbGxpZXMgbW92aW5nKTtcclxuICAgICAgIyB3ZSB3YW50IHRvIHdhaXQgZm9yIHRoZW0gYWxsIGhlcmUgYW5kIG5vdCBhY2NpZGVudGFsbHkgY2F0Y2ggdGhlbVxyXG4gICAgICAjIGluIGEgc3Vic2VxdWVudCB3YWl0Rm9yQW5pbWF0aW9uLlxyXG4gICAgICBzZXRUaW1lb3V0KGNiLCAwKVxyXG4gICAgQGRvbS5hZGRFdmVudExpc3RlbmVyKG5hbWUsIGVuZCkgZm9yIG5hbWUgaW4gbmFtZXNcclxuICAgIHJldHVyblxyXG5cclxuICB0cnlTbGlkZTogKGplbGx5LCBkaXIpIC0+XHJcbiAgICBqZWxsaWVzID0gW2plbGx5XVxyXG4gICAgcmV0dXJuIGlmIEBjaGVja0ZpbGxlZChqZWxsaWVzLCBkaXIsIDApXHJcbiAgICBAYnVzeSA9IHRydWVcclxuICAgIEBtb3ZlKGplbGxpZXMsIGRpciwgMClcclxuICAgIEB3YWl0Rm9yQW5pbWF0aW9uICgpID0+XHJcbiAgICAgIEBjaGVja0ZhbGwgPT5cclxuICAgICAgICBAY2hlY2tGb3JNZXJnZXMoKVxyXG4gICAgICAgIEBidXN5ID0gZmFsc2VcclxuXHJcbiAgbW92ZTogKGplbGxpZXMsIGR4LCBkeSkgLT5cclxuICAgIEBjZWxsc1t5XVt4XSA9IG51bGwgZm9yIFt4LCB5LCBjZWxsXSBpbiBqZWxseS5jZWxsQ29vcmRzKCkgZm9yIGplbGx5IGluIGplbGxpZXNcclxuICAgIGplbGx5LnVwZGF0ZVBvc2l0aW9uKGplbGx5LngrZHgsIGplbGx5LnkrZHkpIGZvciBqZWxseSBpbiBqZWxsaWVzXHJcbiAgICBAY2VsbHNbeV1beF0gPSBjZWxsIGZvciBbeCwgeSwgY2VsbF0gaW4gamVsbHkuY2VsbENvb3JkcygpIGZvciBqZWxseSBpbiBqZWxsaWVzXHJcbiAgICByZXR1cm5cclxuXHJcbiAgY2hlY2tGaWxsZWQ6IChqZWxsaWVzLCBkeCwgZHkpIC0+XHJcbiAgICBkb25lID0gZmFsc2VcclxuICAgIHdoaWxlIG5vdCBkb25lXHJcbiAgICAgIGRvbmUgPSB0cnVlXHJcbiAgICAgIGZvciBqZWxseSBpbiBqZWxsaWVzXHJcbiAgICAgICAgcmV0dXJuIHRydWUgaWYgamVsbHkuaW1tb3ZhYmxlXHJcbiAgICAgICAgZm9yIFt4LCB5LCBjZWxsXSBpbiBqZWxseS5jZWxsQ29vcmRzKClcclxuICAgICAgICAgIG5leHQgPSBAY2VsbHNbeSArIGR5XVt4ICsgZHhdXHJcbiAgICAgICAgICBjb250aW51ZSB1bmxlc3MgbmV4dCAgICAgICAgICAgIyBlbXB0eSBzcGFjZVxyXG4gICAgICAgICAgcmV0dXJuIHRydWUgdW5sZXNzIG5leHQuamVsbHkgICMgd2FsbFxyXG4gICAgICAgICAgY29udGludWUgaWYgbmV4dC5qZWxseSBpbiBqZWxsaWVzXHJcbiAgICAgICAgICBqZWxsaWVzLnB1c2ggbmV4dC5qZWxseVxyXG4gICAgICAgICAgZG9uZSA9IGZhbHNlXHJcbiAgICAgICAgICBicmVha1xyXG4gICAgcmV0dXJuIGZhbHNlXHJcblxyXG4gIGNoZWNrRmFsbDogKGNiKSAtPlxyXG4gICAgbW92ZWQgPSBmYWxzZVxyXG4gICAgdHJ5X2FnYWluID0gdHJ1ZVxyXG4gICAgd2hpbGUgdHJ5X2FnYWluXHJcbiAgICAgIHRyeV9hZ2FpbiA9IGZhbHNlXHJcbiAgICAgIGZvciBqZWxseSBpbiBAamVsbGllc1xyXG4gICAgICAgIGplbGx5c2V0ID0gW2plbGx5XVxyXG4gICAgICAgIGlmIG5vdCBAY2hlY2tGaWxsZWQoamVsbHlzZXQsIDAsIDEpXHJcbiAgICAgICAgICBAbW92ZShqZWxseXNldCwgMCwgMSlcclxuICAgICAgICAgIHRyeV9hZ2FpbiA9IHRydWVcclxuICAgICAgICAgIG1vdmVkID0gdHJ1ZVxyXG4gICAgaWYgbW92ZWRcclxuICAgICAgQHdhaXRGb3JBbmltYXRpb24gY2JcclxuICAgIGVsc2VcclxuICAgICAgY2IoKVxyXG4gICAgcmV0dXJuXHJcblxyXG4gIGNoZWNrRm9yTWVyZ2VzOiAtPlxyXG4gICAgbWVyZ2VkID0gZmFsc2VcclxuICAgIHdoaWxlIEBkb09uZU1lcmdlKClcclxuICAgICAgbWVyZ2VkID0gdHJ1ZVxyXG4gICAgQGNoZWNrRm9yQ29tcGxldGlvbigpIGlmIG1lcmdlZFxyXG4gICAgcmV0dXJuXHJcblxyXG4gIGNoZWNrRm9yQ29tcGxldGlvbjogLT5cclxuICAgIGlmIEBudW1fbW9ub2Nocm9tYXRpY19ibG9ja3MgPD0gQG51bV9jb2xvcnNcclxuICAgICAgYWxlcnQoXCJDb25ncmF0dWxhdGlvbnMhIExldmVsIGNvbXBsZXRlZC5cIilcclxuICAgIHJldHVyblxyXG5cclxuICBkb09uZU1lcmdlOiAtPlxyXG4gICAgZm9yIGplbGx5IGluIEBqZWxsaWVzXHJcbiAgICAgIGZvciBbeCwgeSwgY2VsbF0gaW4gamVsbHkuY2VsbENvb3JkcygpXHJcbiAgICAgICAgIyBPbmx5IGxvb2sgcmlnaHQgYW5kIGRvd247IGxlZnQgYW5kIHVwIGFyZSBoYW5kbGVkIGJ5IHRoYXQgc2lkZVxyXG4gICAgICAgICMgaXRzZWxmIGxvb2tpbmcgcmlnaHQgYW5kIGRvd24uXHJcbiAgICAgICAgZm9yIFtkeCwgZHksIGRpcl0gaW4gW1sxLCAwLCAncmlnaHQnXSwgWzAsIDEsICdkb3duJ11dXHJcbiAgICAgICAgICBvdGhlciA9IEBjZWxsc1t5ICsgZHldW3ggKyBkeF1cclxuICAgICAgICAgIGNvbnRpbnVlIHVubGVzcyBvdGhlciBhbmQgb3RoZXIgaW5zdGFuY2VvZiBKZWxseUNlbGxcclxuICAgICAgICAgIGNvbnRpbnVlIGlmIGNlbGxbJ21lcmdlZCcgKyBkaXJdXHJcbiAgICAgICAgICBjb250aW51ZSB1bmxlc3Mgb3RoZXIuY29sb3IgPT0gY2VsbC5jb2xvclxyXG4gICAgICAgICAgaWYgamVsbHkgIT0gb3RoZXIuamVsbHlcclxuICAgICAgICAgICAgQGplbGxpZXMgPSBAamVsbGllcy5maWx0ZXIgKGopIC0+IGogIT0gb3RoZXIuamVsbHlcclxuICAgICAgICAgIGlmIGNlbGwuY29sb3JfbWFzdGVyICE9IG90aGVyLmNvbG9yX21hc3RlclxyXG4gICAgICAgICAgICBAbnVtX21vbm9jaHJvbWF0aWNfYmxvY2tzIC09IDFcclxuICAgICAgICAgIGNlbGwubWVyZ2VXaXRoIG90aGVyLCBkaXJcclxuICAgICAgICAgIGNlbGxbJ21lcmdlZCcgKyBkaXJdID0gdHJ1ZVxyXG4gICAgICAgICAgcmV0dXJuIHRydWVcclxuICAgIHJldHVybiBmYWxzZVxyXG5cclxuY2xhc3MgV2FsbFxyXG4gIGNvbnN0cnVjdG9yOiAoQGRvbSkgLT5cclxuXHJcbmNsYXNzIEplbGx5Q2VsbFxyXG4gIGNvbnN0cnVjdG9yOiAoQGNvbG9yKSAtPlxyXG4gICAgQGRvbSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2RpdicpXHJcbiAgICBAZG9tLmNsYXNzTmFtZSA9ICdjZWxsIGplbGx5ICcgKyBAY29sb3JcclxuICAgIEB4ID0gMFxyXG4gICAgQHkgPSAwXHJcbiAgICBAY29sb3JfbWFzdGVyID0gdGhpc1xyXG4gICAgQGNvbG9yX21hdGVzID0gW3RoaXNdXHJcblxyXG4gIG1lcmdlV2l0aDogKG90aGVyLCBkaXIpIC0+XHJcbiAgICBib3JkZXJzID0ge1xyXG4gICAgICAnbGVmdCc6ICBbJ2JvcmRlckxlZnQnLCAgICdib3JkZXJSaWdodCddLFxyXG4gICAgICAncmlnaHQnOiBbJ2JvcmRlclJpZ2h0JywgICdib3JkZXJMZWZ0J10sXHJcbiAgICAgICd1cCc6ICAgIFsnYm9yZGVyVG9wJywgICAgJ2JvcmRlckJvdHRvbSddLFxyXG4gICAgICAnZG93bic6ICBbJ2JvcmRlckJvdHRvbScsICdib3JkZXJUb3AnXVxyXG4gICAgfVxyXG4gICAgY29ybmVycyA9IHtcclxuICAgICAgJ2xlZnQnOiBbWydib3JkZXJUb3BMZWZ0UmFkaXVzJywgJ2JvcmRlckJvdHRvbUxlZnRSYWRpdXMnXSxbJ2JvcmRlclRvcFJpZ2h0UmFkaXVzJywgJ2JvcmRlckJvdHRvbVJpZ2h0UmFkaXVzJ11dLFxyXG4gICAgICAncmlnaHQnOiBbWydib3JkZXJUb3BSaWdodFJhZGl1cycsICdib3JkZXJCb3R0b21SaWdodFJhZGl1cyddLFsnYm9yZGVyVG9wTGVmdFJhZGl1cycsICdib3JkZXJCb3R0b21MZWZ0UmFkaXVzJ11dLFxyXG4gICAgICAndXAnOiBbWydib3JkZXJUb3BMZWZ0UmFkaXVzJywgJ2JvcmRlclRvcFJpZ2h0UmFkaXVzJ10sWydib3JkZXJCb3R0b21MZWZ0UmFkaXVzJywgJ2JvcmRlckJvdHRvbVJpZ2h0UmFkaXVzJ11dLFxyXG4gICAgICAnZG93bic6IFtbJ2JvcmRlckJvdHRvbUxlZnRSYWRpdXMnLCAnYm9yZGVyQm90dG9tUmlnaHRSYWRpdXMnXSxbJ2JvcmRlclRvcExlZnRSYWRpdXMnLCAnYm9yZGVyVG9wUmlnaHRSYWRpdXMnXV1cclxuICAgIH1cclxuICAgICMgUmVtb3ZlIGludGVybmFsIGJvcmRlcnMsIHdoZXRoZXIgbWVyZ2luZyB3aXRoIG90aGVyIGplbGx5IG9yIHdhbGwuXHJcbiAgICBAZG9tLnN0eWxlW2JvcmRlcnNbZGlyXVswXV0gPSAnbm9uZSdcclxuICAgIG90aGVyLmRvbS5zdHlsZVtib3JkZXJzW2Rpcl1bMV1dID0gJ25vbmUnXHJcblxyXG4gICAgQGRvbS5zdHlsZVtjb3JuZXJzW2Rpcl1bMF1bMF1dID0gJzAnXHJcbiAgICBAZG9tLnN0eWxlW2Nvcm5lcnNbZGlyXVswXVsxXV0gPSAnMCdcclxuICAgIG90aGVyLmRvbS5zdHlsZVtjb3JuZXJzW2Rpcl1bMV1bMF1dID0gJzAnXHJcbiAgICBvdGhlci5kb20uc3R5bGVbY29ybmVyc1tkaXJdWzFdWzFdXSA9ICcwJ1xyXG5cclxuICAgICMgSWYgbWVyZ2luZyB3aXRoIHdhbGwsIGplbGx5IGJlY29tZXMgaW1tb3ZhYmxlLlxyXG4gICAgQGplbGx5LmltbW92YWJsZSA9IHRydWUgaWYgb3RoZXIgaW5zdGFuY2VvZiBXYWxsXHJcblxyXG4gICAgIyBJZiBtZXJnaW5nIHdpdGggamVsbHksIHVuaWZ5IHRoZSBqZWxsaWVzIGFuZCBjb2xvciBtYXRlcycgbGlzdHMuXHJcbiAgICBpZiBvdGhlciBpbnN0YW5jZW9mIEplbGx5Q2VsbCBhbmQgQGNvbG9yID09IG90aGVyLmNvbG9yIGFuZCBAY29sb3JfbWFzdGVyICE9IG90aGVyLmNvbG9yX21hc3RlclxyXG4gICAgICBvdGhlcl9tYXN0ZXIgPSBvdGhlci5jb2xvcl9tYXN0ZXJcclxuICAgICAgZm9yIGNlbGwgaW4gb3RoZXJfbWFzdGVyLmNvbG9yX21hdGVzXHJcbiAgICAgICAgY2VsbC5jb2xvcl9tYXN0ZXIgPSBAY29sb3JfbWFzdGVyXHJcbiAgICAgIEBjb2xvcl9tYXN0ZXIuY29sb3JfbWF0ZXMgPVxyXG4gICAgICAgIEBjb2xvcl9tYXN0ZXIuY29sb3JfbWF0ZXMuY29uY2F0KG90aGVyX21hc3Rlci5jb2xvcl9tYXRlcylcclxuICAgIGlmIG90aGVyIGluc3RhbmNlb2YgSmVsbHlDZWxsIGFuZCBAamVsbHkgIT0gb3RoZXIuamVsbHlcclxuICAgICAgQGplbGx5Lm1lcmdlKG90aGVyLmplbGx5KVxyXG5cclxuXHJcbmNsYXNzIEplbGx5XHJcbiAgY29uc3RydWN0b3I6IChzdGFnZSwgY2VsbCwgQHgsIEB5KSAtPlxyXG4gICAgQGRvbSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2RpdicpXHJcbiAgICBAdXBkYXRlUG9zaXRpb24oQHgsIEB5KVxyXG4gICAgQGRvbS5jbGFzc05hbWUgPSAnY2VsbCBqZWxseWJveCdcclxuICAgIGNlbGwuamVsbHkgPSB0aGlzXHJcbiAgICBAY2VsbHMgPSBbY2VsbF1cclxuICAgIEBkb20uYXBwZW5kQ2hpbGQoY2VsbC5kb20pXHJcblxyXG4gICAgQGRvbS5hZGRFdmVudExpc3RlbmVyICdjb250ZXh0bWVudScsIChlKSA9PlxyXG4gICAgICBzdGFnZS50cnlTbGlkZSh0aGlzLCAxKVxyXG4gICAgQGRvbS5hZGRFdmVudExpc3RlbmVyICdjbGljaycsIChlKSA9PlxyXG4gICAgICBzdGFnZS50cnlTbGlkZSh0aGlzLCAtMSlcclxuXHJcbiAgICBAZG9tLmFkZEV2ZW50TGlzdGVuZXIgJ3RvdWNoc3RhcnQnLCAoZSkgPT5cclxuICAgICAgQHN0YXJ0ID0gZS50b3VjaGVzWzBdLnBhZ2VYXHJcbiAgICBAZG9tLmFkZEV2ZW50TGlzdGVuZXIgJ3RvdWNobW92ZScsIChlKSA9PlxyXG4gICAgICBkeCA9IGUudG91Y2hlc1swXS5wYWdlWCAtIEBzdGFydFxyXG4gICAgICBpZiBNYXRoLmFicyhkeCkgPiAxMFxyXG4gICAgICAgIGR4ID0gTWF0aC5tYXgoTWF0aC5taW4oZHgsIDEpLCAtMSlcclxuICAgICAgICBzdGFnZS50cnlTbGlkZSh0aGlzLCBkeClcclxuICAgIEBpbW1vdmFibGUgPSBmYWxzZVxyXG5cclxuICBjZWxsQ29vcmRzOiAtPlxyXG4gICAgW0B4ICsgY2VsbC54LCBAeSArIGNlbGwueSwgY2VsbF0gZm9yIGNlbGwgaW4gQGNlbGxzXHJcblxyXG4gIHVwZGF0ZVBvc2l0aW9uOiAoQHgsIEB5KSAtPlxyXG4gICAgbW92ZVRvQ2VsbCBAZG9tLCBAeCwgQHlcclxuXHJcbiAgbWVyZ2U6IChvdGhlcikgLT5cclxuICAgICMgUmVwb3NpdGlvbiBvdGhlcidzIGNlbGxzIGFzIGNoaWxkcmVuIG9mIHRoaXMgamVsbHkuXHJcbiAgICBkeCA9IG90aGVyLnggLSB0aGlzLnhcclxuICAgIGR5ID0gb3RoZXIueSAtIHRoaXMueVxyXG4gICAgZm9yIGNlbGwgaW4gb3RoZXIuY2VsbHNcclxuICAgICAgQGNlbGxzLnB1c2ggY2VsbFxyXG4gICAgICBjZWxsLnggKz0gZHhcclxuICAgICAgY2VsbC55ICs9IGR5XHJcbiAgICAgIGNlbGwuamVsbHkgPSB0aGlzXHJcbiAgICAgIG1vdmVUb0NlbGwgY2VsbC5kb20sIGNlbGwueCwgY2VsbC55XHJcbiAgICAgIEBkb20uYXBwZW5kQ2hpbGQoY2VsbC5kb20pXHJcblxyXG4gICAgQGltbW92YWJsZSA9IHRydWUgaWYgb3RoZXIuaW1tb3ZhYmxlXHJcbiAgICAjIERlbGV0ZSByZWZlcmVuY2VzIGZyb20vdG8gb3RoZXIuXHJcbiAgICBvdGhlci5jZWxscyA9IG51bGxcclxuICAgIG90aGVyLmRvbS5wYXJlbnROb2RlLnJlbW92ZUNoaWxkKG90aGVyLmRvbSlcclxuICAgIHJldHVyblxyXG5cclxubGV2ZWwgPSBwYXJzZUludChsb2NhdGlvbi5zZWFyY2guc3Vic3RyKDEpLCAxMCkgb3IgMVxyXG5zdGFnZSA9IG5ldyBTdGFnZShkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbWFwJyksIGxldmVsc1tsZXZlbC0xXSlcclxud2luZG93LnN0YWdlID0gc3RhZ2VcclxuXHJcbmxldmVsUGlja2VyID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2xldmVsJylcclxuZm9yIGkgaW4gWzEuLmxldmVscy5sZW5ndGhdXHJcbiAgb3B0aW9uID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnb3B0aW9uJylcclxuICBvcHRpb24udmFsdWUgPSBpXHJcbiAgb3B0aW9uLmFwcGVuZENoaWxkKGRvY3VtZW50LmNyZWF0ZVRleHROb2RlKFwiTGV2ZWwgI3tpfVwiKSk7XHJcbiAgbGV2ZWxQaWNrZXIuYXBwZW5kQ2hpbGQob3B0aW9uKVxyXG5sZXZlbFBpY2tlci52YWx1ZSA9IGxldmVsXHJcbmxldmVsUGlja2VyLmFkZEV2ZW50TGlzdGVuZXIgJ2NoYW5nZScsICgpIC0+XHJcbiAgbG9jYXRpb24uc2VhcmNoID0gJz8nICsgbGV2ZWxQaWNrZXIudmFsdWVcclxuXHJcbmRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdyZXNldCcpLmFkZEV2ZW50TGlzdGVuZXIgJ2NsaWNrJywgLT5cclxuICBzdGFnZS5kb20uaW5uZXJIVE1MID0gJydcclxuICBzdGFnZSA9IG5ldyBTdGFnZShzdGFnZS5kb20sIGxldmVsc1tsZXZlbC0xXSlcclxuIl0sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7QUFBQTtFQUFBLElBQUFBLFNBQUE7SUFBQUMsS0FBQTtJQUFBQyxTQUFBO0lBQUFDLEtBQUE7SUFBQUMsSUFBQTtJQUFBQyxDQUFBO0lBQUFDLENBQUE7SUFBQUMsS0FBQTtJQUFBQyxXQUFBO0lBQUFDLE1BQUE7SUFBQUMsVUFBQTtJQUFBQyxNQUFBO0lBQUFDLEdBQUE7SUFBQUMsS0FBQTtJQUFBQyxPQUFBLE1BQUFBLE9BQUE7RUFBQUwsTUFBQSxHQUFTOztFQUVQLENBQUUsZ0JBQUYsRUFDRSxnQkFERixFQUVFLGdCQUZGLEVBR0UsZ0JBSEYsRUFJRSxnQkFKRixFQUtFLGdCQUxGLEVBTUUsZ0JBTkYsRUFPRSxnQkFQRixDQUZPLEVBV1AsQ0FBRSxnQkFBRixFQUNFLGdCQURGLEVBRUUsZ0JBRkYsRUFHRSxnQkFIRixFQUlFLGdCQUpGLEVBS0UsZ0JBTEYsRUFNRSxnQkFORixFQU9FLGdCQVBGLENBWE8sRUFvQlAsQ0FBRSxnQkFBRixFQUNFLGdCQURGLEVBRUUsZ0JBRkYsRUFHRSxnQkFIRixFQUlFLGdCQUpGLEVBS0UsZ0JBTEYsRUFNRSxnQkFORixFQU9FLGdCQVBGLENBcEJPLEVBNkJQLENBQUUsZ0JBQUYsRUFDRSxnQkFERixFQUVFLGdCQUZGLEVBR0UsZ0JBSEYsRUFJRSxnQkFKRixFQUtFLGdCQUxGLEVBTUUsZ0JBTkYsRUFPRSxnQkFQRixFQVFFLGdCQVJGLEVBU0UsZ0JBVEYsQ0E3Qk87O0VBeUNQLENBQUUsZ0JBQUYsRUFDRSxnQkFERixFQUVFLGdCQUZGLEVBR0UsZ0JBSEYsRUFJRSxnQkFKRixFQUtFLGdCQUxGLEVBTUUsZ0JBTkYsRUFPRSxnQkFQRixFQVFFLGdCQVJGLENBekNPLEVBbURQLENBQUUsZ0JBQUYsRUFDRSxnQkFERixFQUVFLGdCQUZGLEVBR0UsZ0JBSEYsRUFJRSxnQkFKRixFQUtFLGdCQUxGLEVBTUUsZ0JBTkYsRUFPRSxnQkFQRixFQVFFLGdCQVJGLEVBU0UsZ0JBVEYsQ0FuRE8sRUFvRVA7Ozs7Ozs7RUFBRSxDQUFFLGdCQUFGLEVBQ0UsZ0JBREYsRUFFRSxnQkFGRixFQUdFLGdCQUhGLEVBSUUsZ0JBSkYsRUFLRSxnQkFMRixFQU1FLGdCQU5GLEVBT0UsZ0JBUEYsRUFRRSxnQkFSRixFQVNFLGdCQVRGLENBQUYsRUFVRSxDQUNFO0lBQUVNLENBQUEsRUFBRSxDQUFKO0lBQU9DLENBQUEsRUFBRSxDQUFUO0lBQVlDLEdBQUEsRUFBSTtFQUFoQixDQURGLEVBRUU7SUFBRUYsQ0FBQSxFQUFFLENBQUo7SUFBT0MsQ0FBQSxFQUFFLENBQVQ7SUFBWUMsR0FBQSxFQUFJO0VBQWhCLENBRkYsQ0FWRixDQXBFTyxFQW9GUCxDQUFFLENBQUUsZ0JBQUYsRUFDRSxnQkFERixFQUVFLGdCQUZGLEVBR0UsZ0JBSEYsRUFJRSxnQkFKRixFQUtFLGdCQUxGLEVBTUUsZ0JBTkYsRUFPRSxnQkFQRixFQVFFLGdCQVJGLENBQUYsRUFTRSxDQUNFO0lBQUVGLENBQUEsRUFBRSxDQUFKO0lBQU9DLENBQUEsRUFBRSxDQUFUO0lBQVlDLEdBQUEsRUFBSTtFQUFoQixDQURGLEVBRUU7SUFBRUYsQ0FBQSxFQUFFLENBQUo7SUFBT0MsQ0FBQSxFQUFFLENBQVQ7SUFBWUMsR0FBQSxFQUFJO0VBQWhCLENBRkYsQ0FURixDQXBGTyxFQW1HUCxDQUFFLENBQUUsZ0JBQUYsRUFDRSxnQkFERixFQUVFLGdCQUZGLEVBR0UsZ0JBSEYsRUFJRSxnQkFKRixFQUtFLGdCQUxGLEVBTUUsZ0JBTkYsRUFPRSxnQkFQRixDQUFGLEVBUUUsQ0FDRTtJQUFFRixDQUFBLEVBQUUsQ0FBSjtJQUFPQyxDQUFBLEVBQUUsQ0FBVDtJQUFZQyxHQUFBLEVBQUk7RUFBaEIsQ0FERixDQVJGLENBbkdPLEVBaUhQOztFQUFFLENBQUUsZ0JBQUYsRUFDRSxnQkFERixFQUVFLGdCQUZGLEVBR0UsZ0JBSEYsRUFJRSxnQkFKRixFQUtFLGdCQUxGLEVBTUUsZ0JBTkYsRUFPRSxnQkFQRixFQVFFLGdCQVJGLEVBU0UsZ0JBVEYsQ0FBRixFQVVFLENBQ0U7SUFBRUYsQ0FBQSxFQUFFLEVBQUo7SUFBUUMsQ0FBQSxFQUFFLENBQVY7SUFBYUMsR0FBQSxFQUFJO0VBQWpCLENBREYsRUFFRTtJQUFFRixDQUFBLEVBQUUsRUFBSjtJQUFRQyxDQUFBLEVBQUUsQ0FBVjtJQUFhQyxHQUFBLEVBQUk7RUFBakIsQ0FGRixDQVZGLENBakhPLEVBaUlQLENBQUUsQ0FBRSxnQkFBRixFQUNFLGdCQURGLEVBRUUsZ0JBRkYsRUFHRSxnQkFIRixFQUlFLGdCQUpGLEVBS0UsZ0JBTEYsRUFNRSxnQkFORixFQU9FLGdCQVBGLEVBUUUsZ0JBUkYsRUFTRSxnQkFURixDQUFGLEVBVUUsQ0FDRTtJQUFFRixDQUFBLEVBQUUsRUFBSjtJQUFRQyxDQUFBLEVBQUUsQ0FBVjtJQUFhQyxHQUFBLEVBQUk7RUFBakIsQ0FERixFQUVFO0lBQUVGLENBQUEsRUFBRSxDQUFKO0lBQU9DLENBQUEsRUFBRSxDQUFUO0lBQVlDLEdBQUEsRUFBSTtFQUFoQixDQUZGLEVBR0U7SUFBRUYsQ0FBQSxFQUFFLEVBQUo7SUFBUUMsQ0FBQSxFQUFFLENBQVY7SUFBYUMsR0FBQSxFQUFJO0VBQWpCLENBSEYsQ0FWRixDQWpJTyxFQWtKUCxDQUFFLENBQUUsZ0JBQUYsRUFDRSxnQkFERixFQUVFLGdCQUZGLEVBR0UsZ0JBSEYsRUFJRSxnQkFKRixFQUtFLGdCQUxGLEVBTUUsZ0JBTkYsRUFPRSxnQkFQRixFQVFFLGdCQVJGLEVBU0UsZ0JBVEYsQ0FBRixFQVVFLENBQ0U7SUFBRUYsQ0FBQSxFQUFFLEVBQUo7SUFBUUMsQ0FBQSxFQUFFLENBQVY7SUFBYUMsR0FBQSxFQUFJO0VBQWpCLENBREYsQ0FWRixDQWxKTyxFQWlLUCxDQUFFLGdCQUFGLEVBQ0UsZ0JBREYsRUFFRSxnQkFGRixFQUdFLGdCQUhGLEVBSUUsZ0JBSkYsRUFLRSxnQkFMRixFQU1FLGdCQU5GLEVBT0UsZ0JBUEYsQ0FqS08sRUEwS1AsQ0FBRSxDQUFFLGdCQUFGLEVBQ0UsZ0JBREYsRUFFRSxnQkFGRixFQUdFLGdCQUhGLEVBSUUsZ0JBSkYsRUFLRSxnQkFMRixFQU1FLGdCQU5GLEVBT0UsZ0JBUEYsRUFRRSxnQkFSRixFQVNFLGdCQVRGLENBQUYsRUFVRSxDQUNFO0lBQUVGLENBQUEsRUFBRSxDQUFKO0lBQU9DLENBQUEsRUFBRSxDQUFUO0lBQVlDLEdBQUEsRUFBSTtFQUFoQixDQURGLEVBRUU7SUFBRUYsQ0FBQSxFQUFFLENBQUo7SUFBT0MsQ0FBQSxFQUFFLENBQVQ7SUFBWUMsR0FBQSxFQUFJO0VBQWhCLENBRkYsQ0FWRixDQTFLTyxFQTJMUDs7RUFBRSxDQUFFLGdCQUFGLEVBQ0UsZ0JBREYsRUFFRSxnQkFGRixFQUdFLGdCQUhGLEVBSUUsZ0JBSkYsRUFLRSxnQkFMRixFQU1FLGdCQU5GLEVBT0UsZ0JBUEYsRUFRRSxnQkFSRixFQVNFLGdCQVRGLENBQUYsRUFVRSxDQUNFO0lBQUVGLENBQUEsRUFBRSxDQUFKO0lBQU9DLENBQUEsRUFBRSxDQUFUO0lBQVlDLEdBQUEsRUFBSTtFQUFoQixDQURGLEVBRUU7SUFBRUYsQ0FBQSxFQUFFLENBQUo7SUFBT0MsQ0FBQSxFQUFFLENBQVQ7SUFBWUMsR0FBQSxFQUFJO0VBQWhCLENBRkYsRUFHRTtJQUFFRixDQUFBLEVBQUUsQ0FBSjtJQUFPQyxDQUFBLEVBQUUsQ0FBVDtJQUFZQyxHQUFBLEVBQUk7RUFBaEIsQ0FIRixDQVZGLENBM0xPLEVBNE1QLENBQUUsQ0FBRSxnQkFBRixFQUNFLGdCQURGLEVBRUUsZ0JBRkYsRUFHRSxnQkFIRixFQUlFLGdCQUpGLEVBS0UsZ0JBTEYsRUFNRSxnQkFORixFQU9FLGdCQVBGLEVBUUUsZ0JBUkYsRUFTRSxnQkFURixDQUFGLEVBVUUsQ0FDRTtJQUFFRixDQUFBLEVBQUUsQ0FBSjtJQUFPQyxDQUFBLEVBQUUsQ0FBVDtJQUFZQyxHQUFBLEVBQUk7RUFBaEIsQ0FERixDQVZGLENBNU1PLEVBMk5QLENBQUUsQ0FBRSxnQkFBRixFQUNFLGdCQURGLEVBRUUsZ0JBRkYsRUFHRSxnQkFIRixFQUlFLGdCQUpGLEVBS0UsZ0JBTEYsRUFNRSxnQkFORixFQU9FLGdCQVBGLEVBUUUsZ0JBUkYsRUFTRSxnQkFURixDQUFGLEVBVUUsQ0FDRTtJQUFFRixDQUFBLEVBQUUsRUFBSjtJQUFRQyxDQUFBLEVBQUUsQ0FBVjtJQUFhQyxHQUFBLEVBQUk7RUFBakIsQ0FERixFQUVFO0lBQUVGLENBQUEsRUFBRSxFQUFKO0lBQVFDLENBQUEsRUFBRSxDQUFWO0lBQWFDLEdBQUEsRUFBSTtFQUFqQixDQUZGLENBVkYsQ0EzTk8sRUEyT1AsQ0FBRSxDQUFFLGdCQUFGLEVBQ0UsZ0JBREYsRUFFRSxnQkFGRixFQUdFLGdCQUhGLEVBSUUsZ0JBSkYsRUFLRSxnQkFMRixFQU1FLGdCQU5GLEVBT0UsZ0JBUEYsRUFRRSxnQkFSRixFQVNFLGdCQVRGLENBQUYsRUFVRSxDQUNFO0lBQUVGLENBQUEsRUFBRSxFQUFKO0lBQVFDLENBQUEsRUFBRSxDQUFWO0lBQWFDLEdBQUEsRUFBSTtFQUFqQixDQURGLENBVkYsQ0EzT08sRUEwUFAsQ0FBRSxDQUFFLGdCQUFGLEVBQ0UsZ0JBREYsRUFFRSxnQkFGRixFQUdFLGdCQUhGLEVBSUUsZ0JBSkYsRUFLRSxnQkFMRixFQU1FLGdCQU5GLEVBT0UsZ0JBUEYsRUFRRSxnQkFSRixFQVNFLGdCQVRGLENBQUYsRUFVRSxDQUNFO0lBQUVGLENBQUEsRUFBRSxDQUFKO0lBQU9DLENBQUEsRUFBRSxDQUFUO0lBQVlDLEdBQUEsRUFBSTtFQUFoQixDQURGLEVBRUU7SUFBRUYsQ0FBQSxFQUFFLENBQUo7SUFBT0MsQ0FBQSxFQUFFLENBQVQ7SUFBWUMsR0FBQSxFQUFJO0VBQWhCLENBRkYsRUFHRTtJQUFFRixDQUFBLEVBQUUsQ0FBSjtJQUFPQyxDQUFBLEVBQUUsQ0FBVDtJQUFZQyxHQUFBLEVBQUk7RUFBaEIsQ0FIRixFQUlFO0lBQUVGLENBQUEsRUFBRSxDQUFKO0lBQU9DLENBQUEsRUFBRSxDQUFUO0lBQVlDLEdBQUEsRUFBSTtFQUFoQixDQUpGLEVBS0U7SUFBRUYsQ0FBQSxFQUFFLENBQUo7SUFBT0MsQ0FBQSxFQUFFLENBQVQ7SUFBWUMsR0FBQSxFQUFJO0VBQWhCLENBTEYsRUFNRTtJQUFFRixDQUFBLEVBQUUsQ0FBSjtJQUFPQyxDQUFBLEVBQUUsQ0FBVDtJQUFZQyxHQUFBLEVBQUk7RUFBaEIsQ0FORixFQU9FO0lBQUVGLENBQUEsRUFBRSxDQUFKO0lBQU9DLENBQUEsRUFBRSxDQUFUO0lBQVlDLEdBQUEsRUFBSTtFQUFoQixDQVBGLENBVkYsQ0ExUE8sRUFnUlA7O0VBQUUsQ0FBRSxnQkFBRixFQUNFLGdCQURGLEVBRUUsZ0JBRkYsRUFHRSxnQkFIRixFQUlFLGdCQUpGLEVBS0UsZ0JBTEYsRUFNRSxnQkFORixFQU9FLGdCQVBGLEVBUUUsZ0JBUkYsRUFTRSxnQkFURixDQUFGLEVBVUUsQ0FDRTtJQUFFRixDQUFBLEVBQUUsRUFBSjtJQUFRQyxDQUFBLEVBQUUsQ0FBVjtJQUFhQyxHQUFBLEVBQUk7RUFBakIsQ0FERixDQVZGLENBaFJPLEM7RUFpU1RqQixTQUFBLEdBQVk7RUFFWlUsVUFBQSxHQUFhLFNBQUFBLFdBQUNRLEdBQUQsRUFBTUgsQ0FBTixFQUFTQyxDQUFUO0lBQ1hFLEdBQUcsQ0FBQ0MsS0FBSyxDQUFDQyxJQUFWLEdBQWlCTCxDQUFBLEdBQUlmLFNBQUosR0FBZ0I7V0FDakNrQixHQUFHLENBQUNDLEtBQUssQ0FBQ0UsR0FBVixHQUFnQkwsQ0FBQSxHQUFJaEIsU0FBSixHQUFnQjtFQUZyQjtFQUlQRyxLQUFBO0lBQ0osU0FBQUEsTUFBYW1CLElBQUEsRUFBT0MsR0FBUDtNQUFBLElBQUFDLEtBQUE7TUFBQUMsZUFBQSxPQUFBdEIsS0FBQTtNQUNmLElBQUF1QixPQUFBLEVBQUFDLEtBQUEsRUFBQXJCLENBQUEsRUFBQXNCLEdBQUEsRUFBQUMsaUJBQUEsRUFBQWpCLEdBQUE7TUFEZ0IsSUFBQyxDQUFBTSxHQUFBLEdBQUFJLElBQUE7TUFDYixJQUFDLENBQUFRLE9BQUQsR0FBVztNQUNYSixPQUFBLEdBQVU7TUFDVixJQUFHSCxHQUFHLENBQUMsQ0FBRCxDQUFILFlBQWtCUSxLQUFyQjtRQUNFTCxPQUFBLEdBQVVILEdBQUcsQ0FBQyxDQUFEO1FBQ2JBLEdBQUEsR0FBTUEsR0FBRyxDQUFDLENBQUQ7O01BQ1gsSUFBQyxDQUFBUyx3QkFBRCxHQUE0QjtNQUM1QixJQUFDLENBQUFDLFVBQUQsR0FBYztNQUNkLElBQUMsQ0FBQUMsT0FBRCxDQUFTWCxHQUFULEVBQWNHLE9BQWQ7O01BR0EsSUFBQyxDQUFBUyxJQUFELEdBQVE7TUFDUk4saUJBQUEsR0FBb0IsU0FBQUEsa0JBQUNPLENBQUQ7UUFDbEJBLENBQUMsQ0FBQ0MsY0FBRjtRQUNBLElBQXVCYixLQUFDLENBQUFXLElBQXhCO2lCQUFBQyxDQUFDLENBQUNFLGVBQUY7O01BRmtCO01BR3BCMUIsR0FBQTtNQUFBLEtBQUFOLENBQUEsTUFBQXNCLEdBQUEsR0FBQWhCLEdBQUEsQ0FBQTJCLE1BQUEsRUFBQWpDLENBQUEsR0FBQXNCLEdBQUEsRUFBQXRCLENBQUE7O1FBQ0UsSUFBQyxDQUFBWSxHQUFHLENBQUNzQixnQkFBTCxDQUFzQmIsS0FBdEIsRUFBNkJFLGlCQUE3QixFQUFnRCxJQUFoRDtNQURGO01BR0EsSUFBQyxDQUFBWSxjQUFEO0lBbEJXO0lBQUFDLFlBQUEsQ0FBQXZDLEtBQUE7TUFBQXdDLEdBQUE7TUFBQUMsS0FBQSxFQW9CYixTQUFBVixRQUFVWCxHQUFELEVBQU1HLE9BQU47UUFDWCxJQUFBbUIsSUFBQSxFQUFBQyxTQUFBLEVBQUFDLEtBQUEsRUFBQUMsTUFBQSxFQUFBQyxLQUFBLEVBQUFDLEdBQUEsRUFBQUMsS0FBQSxFQUFBQyxFQUFBLEVBQUFDLEVBQUEsRUFBQXRDLENBQUEsRUFBQUMsQ0FBQTtRQUFJbUMsS0FBQSxHQUFRRyxRQUFRLENBQUNDLGFBQVQsQ0FBdUIsT0FBdkI7UUFDUixJQUFDLENBQUFyQyxHQUFHLENBQUNzQyxXQUFMLENBQWlCTCxLQUFqQjtRQUNBSCxNQUFBLEdBQVM7UUFDVCxJQUFDLENBQUFTLEtBQUQ7O1VBQVNDLE9BQUE7VUFBQSxLQUFTMUMsQ0FBQSxHQUFBVixDQUFBLE1BQUFNLEdBQUEsR0FBQVcsR0FBQSxDQUFBZ0IsTUFBQSxPQUFBM0IsR0FBQSxHQUFBTixDQUFBLEdBQUFNLEdBQUEsR0FBQU4sQ0FBQSxHQUFBTSxHQUFBLEVBQUFJLENBQUEsUUFBQUosR0FBQSxLQUFBTixDQUFBLEtBQUFBLENBQVQ7WUFDUDRDLEdBQUEsR0FBTTNCLEdBQUcsQ0FBQ1AsQ0FBRCxDQUFHLENBQUMyQyxLQUFQLENBQWEsRUFBYjtZQUNOTixFQUFBLEdBQUtDLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixJQUF2QjtZQUNMSixLQUFLLENBQUNLLFdBQU4sQ0FBa0JILEVBQWxCOzs7Y0FDQU8sUUFBQTtjQUFBLEtBQVM3QyxDQUFBLEdBQUE4QyxDQUFBLE1BQUFDLElBQUEsR0FBQVosR0FBQSxDQUFBWCxNQUFBLE9BQUF1QixJQUFBLEdBQUFELENBQUEsR0FBQUMsSUFBQSxHQUFBRCxDQUFBLEdBQUFDLElBQUEsRUFBQS9DLENBQUEsUUFBQStDLElBQUEsS0FBQUQsQ0FBQSxLQUFBQSxDQUFUO2dCQUNFZCxLQUFBLEdBQVE7Z0JBQ1JELFNBQUEsR0FBWTtnQkFDWkQsSUFBQSxHQUFPO2dCQUNQTyxFQUFBLEdBQUtFLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixJQUF2QjtnQkFDTCxRQUFPTCxHQUFHLENBQUNuQyxDQUFELENBQVY7a0JBQUEsS0FDTyxHQURQO29CQUVJK0IsU0FBQSxHQUFZO29CQUNaRCxJQUFBLEdBQU8sSUFBSXpDLElBQUosQ0FBU2dELEVBQVQ7b0JBRko7a0JBRFAsS0FJTyxHQUpQO29CQUlnQkwsS0FBQSxHQUFRO29CQUFqQjtrQkFKUCxLQUtPLEdBTFA7b0JBS2dCQSxLQUFBLEdBQVE7b0JBQWpCO2tCQUxQLEtBTU8sR0FOUDtvQkFNZ0JBLEtBQUEsR0FBUTtvQkFBakI7a0JBTlAsS0FPTyxHQVBQO2tCQUFBLEtBT1csR0FQWDtrQkFBQSxLQU9lLEdBUGY7a0JBQUEsS0FPbUIsR0FQbkI7a0JBQUEsS0FPdUIsR0FQdkI7a0JBQUEsS0FPMkIsR0FQM0I7a0JBQUEsS0FPK0IsR0FQL0I7a0JBQUEsS0FPbUMsR0FQbkM7a0JBQUEsS0FPdUMsR0FQdkM7a0JBQUEsS0FPMkMsR0FQM0M7b0JBUUlBLEtBQUEsR0FBUSxVQUFVRyxHQUFHLENBQUNuQyxDQUFEO2dCQVJ6QjtnQkFTQXFDLEVBQUUsQ0FBQ1csU0FBSCxHQUFlakIsU0FBQTtnQkFDZk8sRUFBRSxDQUFDRyxXQUFILENBQWVKLEVBQWY7Z0JBQ0EsSUFBR0wsS0FBSDtrQkFDRUYsSUFBQSxHQUFPLElBQUkzQyxTQUFKLENBQWM2QyxLQUFkO2tCQUNQRSxLQUFBLEdBQVEsSUFBSWhELEtBQUosQ0FBVSxJQUFWLEVBQWdCNEMsSUFBaEIsRUFBc0I5QixDQUF0QixFQUF5QkMsQ0FBekI7a0JBQ1IsSUFBQyxDQUFBRSxHQUFHLENBQUNzQyxXQUFMLENBQWlCUCxLQUFLLENBQUMvQixHQUF2QjtrQkFDQSxJQUFDLENBQUFZLE9BQU8sQ0FBQ2tDLElBQVQsQ0FBY2YsS0FBZDtrQkFDQSxJQUFDLENBQUFqQix3QkFBRCxJQUE2QjtrQkFDN0IsTUFBdUJlLEtBQUEsSUFBU0MsTUFBQSxDQUFoQztvQkFBQSxJQUFDLENBQUFmLFVBQUQsSUFBYzs7a0JBQ2RlLE1BQU0sQ0FBQ0QsS0FBRCxDQUFOLEdBQWdCOzs4QkFDbEJGLElBQUE7Y0F4QkY7OztVQUpPOzs7UUE2QlQsSUFBQyxDQUFBb0IsVUFBRDtRQUNBLElBQUMsQ0FBQUMsWUFBRCxDQUFjeEMsT0FBZDtNQWxDTztJQUFBO01BQUFpQixHQUFBO01BQUFDLEtBQUEsRUFxQ1QsU0FBQXNCLGFBQWV4QyxPQUFEO1FBQ2hCLElBQUF5QyxNQUFBLEVBQUFDLEtBQUEsRUFBQXRCLFNBQUEsRUFBQUUsTUFBQSxFQUFBcUIsVUFBQSxFQUFBQyxFQUFBLEVBQUFDLEVBQUEsRUFBQXRCLEtBQUEsRUFBQTNDLENBQUEsRUFBQXNCLEdBQUEsRUFBQTRDLEVBQUEsRUFBQUMsS0FBQSxFQUFBQyxRQUFBO1FBQUlMLFVBQUEsR0FBYTtVQUNYLFFBQVMsQ0FBQyxDQUFDLENBQUYsRUFBTSxDQUFOLEVBQVMsV0FBVCxFQUFzQixrQkFBdEIsQ0FERTtVQUVYLFNBQVMsQ0FBRSxDQUFGLEVBQU0sQ0FBTixFQUFTLFlBQVQsRUFBdUIsaUJBQXZCLENBRkU7VUFHWCxNQUFTLENBQUUsQ0FBRixFQUFLLENBQUMsQ0FBTixFQUFTLFNBQVQsRUFBb0IsbUJBQXBCLENBSEU7VUFJWCxRQUFTLENBQUUsQ0FBRixFQUFNLENBQU4sRUFBUyxXQUFULEVBQXNCLGdCQUF0QjtRQUpFO1FBTWJyQixNQUFBLEdBQVM7VUFDUCxPQUFTLG1CQURGO1VBRVAsU0FBUyxxQkFGRjtVQUdQLFFBQVM7UUFIRjtRQUtULEtBQUExQyxDQUFBLE1BQUFzQixHQUFBLEdBQUFGLE9BQUEsQ0FBQWEsTUFBQSxFQUFBakMsQ0FBQSxHQUFBc0IsR0FBQSxFQUFBdEIsQ0FBQTs7VUFDRWdFLEVBQUEsR0FBS0QsVUFBVSxDQUFDRixNQUFNLENBQUNsRCxHQUFSLENBQVksQ0FBQyxDQUFEO1VBQzNCc0QsRUFBQSxHQUFLRixVQUFVLENBQUNGLE1BQU0sQ0FBQ2xELEdBQVIsQ0FBWSxDQUFDLENBQUQ7VUFDM0I2QixTQUFBLEdBQVl1QixVQUFVLENBQUNGLE1BQU0sQ0FBQ2xELEdBQVIsQ0FBWSxDQUFDLENBQUQ7VUFDbEN5RCxRQUFBLEdBQVdMLFVBQVUsQ0FBQ0YsTUFBTSxDQUFDbEQsR0FBUixDQUFZLENBQUMsQ0FBRDtVQUVqQ3VELEVBQUEsR0FBSyxJQUFDLENBQUFmLEtBQUssQ0FBQ1UsTUFBTSxDQUFDbkQsQ0FBUixDQUFVLENBQUNtRCxNQUFNLENBQUNwRCxDQUFSO1VBQ3JCMEQsS0FBQSxHQUFRLElBQUMsQ0FBQWhCLEtBQUssQ0FBQ1UsTUFBTSxDQUFDbkQsQ0FBUCxHQUFXdUQsRUFBWixDQUFlLENBQUNKLE1BQU0sQ0FBQ3BELENBQVAsR0FBV3VELEVBQVo7VUFDN0JFLEVBQUUsQ0FBQ0csU0FBSCxDQUFhRixLQUFiLEVBQW9CTixNQUFNLENBQUNsRCxHQUEzQjs7VUFHQW1ELEtBQUEsR0FBUWQsUUFBUSxDQUFDQyxhQUFULENBQXVCLEtBQXZCO1VBQ1JhLEtBQUssQ0FBQ2pELEtBQUssQ0FBQ3VELFFBQUQsQ0FBWCxHQUF3QjFCLE1BQU0sQ0FBQ3dCLEVBQUUsQ0FBQ3pCLEtBQUo7VUFDOUJxQixLQUFLLENBQUNMLFNBQU4sR0FBa0JqQixTQUFBO1VBQ2xCMkIsS0FBSyxDQUFDdkQsR0FBRyxDQUFDc0MsV0FBVixDQUFzQlksS0FBdEI7UUFkRjtlQWVBLElBQUMsQ0FBQXRDLE9BQUQ7O1VBQVlsQixHQUFBLFFBQUFrQixPQUFBO1VBQUE0QixPQUFBO1VBQUEsS0FBQUcsQ0FBQSxNQUFBZSxJQUFBLEdBQUFoRSxHQUFBLENBQUEyQixNQUFBLEVBQUFzQixDQUFBLEdBQUFlLElBQUEsRUFBQWYsQ0FBQTs7Z0JBQWlDWixLQUFLLENBQUNRLEtBQUE7MkJBQXZDUixLQUFBOztVQUFBOzs7TUEzQkE7SUFBQTtNQUFBTixHQUFBO01BQUFDLEtBQUEsRUE2QmQsU0FBQXFCLFdBQUEsRUFBWTtRQUNkLElBQUFZLElBQUEsRUFBQUMsTUFBQSxFQUFBakMsSUFBQSxFQUFBeUIsRUFBQSxFQUFBQyxFQUFBLEVBQUFRLEtBQUEsRUFBQXpFLENBQUEsRUFBQXVELENBQUEsRUFBQWpDLEdBQUEsRUFBQW9ELENBQUEsRUFBQVAsS0FBQSxFQUFBN0QsR0FBQSxFQUFBa0QsSUFBQSxFQUFBbUIsSUFBQSxFQUFBQyxJQUFBLEVBQUFuRSxDQUFBLEVBQUFDLENBQUE7UUFBSSxLQUFTQSxDQUFBLEdBQUFWLENBQUEsTUFBQU0sR0FBQSxRQUFBNkMsS0FBQSxDQUFBbEIsTUFBQSxPQUFBM0IsR0FBQSxHQUFBTixDQUFBLEdBQUFNLEdBQUEsR0FBQU4sQ0FBQSxHQUFBTSxHQUFBLEVBQUFJLENBQUEsUUFBQUosR0FBQSxLQUFBTixDQUFBLEtBQUFBLENBQVQ7VUFDRSxLQUFTUyxDQUFBLEdBQUE4QyxDQUFBLE1BQUFDLElBQUEsUUFBQUwsS0FBQSxJQUFBbEIsTUFBQSxPQUFBdUIsSUFBQSxHQUFBRCxDQUFBLEdBQUFDLElBQUEsR0FBQUQsQ0FBQSxHQUFBQyxJQUFBLEVBQUEvQyxDQUFBLFFBQUErQyxJQUFBLEtBQUFELENBQUEsS0FBQUEsQ0FBVDtZQUNFaEIsSUFBQSxHQUFPLElBQUMsQ0FBQVksS0FBSyxDQUFDekMsQ0FBRCxDQUFHLENBQUNELENBQUQ7WUFDaEIsTUFBZ0I4QixJQUFBLFlBQWdCekMsSUFBQSxDQUFoQztjQUFBOztZQUNBMEUsTUFBQSxHQUFTO1lBQ1RDLEtBQUEsR0FBUSxDQUNOLENBQUMsY0FBRCxFQUFrQixDQUFsQixFQUFzQixDQUF0QixDQURNLEVBRU4sQ0FBQyxXQUFELEVBQWtCLENBQWxCLEVBQXFCLENBQUMsQ0FBdEIsQ0FGTSxFQUdOLENBQUMsWUFBRCxFQUFpQixDQUFDLENBQWxCLEVBQXNCLENBQXRCLENBSE0sRUFJTixDQUFDLGFBQUQsRUFBa0IsQ0FBbEIsRUFBc0IsQ0FBdEIsQ0FKTTtZQU1SLEtBQUFDLENBQUEsTUFBQXBELEdBQUEsR0FBQW1ELEtBQUEsQ0FBQXhDLE1BQUEsRUFBQXlDLENBQUEsR0FBQXBELEdBQUEsRUFBQW9ELENBQUE7Y0FBQSxJQUFBRyxRQUFBLEdBQUFDLGNBQUEsQ0FBSUwsS0FBQSxDQUFBQyxDQUFBO2NBQUNILElBQUQsR0FBQU0sUUFBQTtjQUFPYixFQUFQLEdBQUFhLFFBQUE7Y0FBV1osRUFBWCxHQUFBWSxRQUFBO2NBQ0YsTUFBZ0IsTUFBQUYsSUFBQSxHQUFNakUsQ0FBQSxHQUFFdUQsRUFBQSxDQUFSLElBQUFVLElBQUEsR0FBYyxJQUFDLENBQUF4QixLQUFLLENBQUNsQixNQUFyQixDQUFoQjtnQkFBQTs7Y0FDQSxNQUFnQixNQUFBMkMsSUFBQSxHQUFNbkUsQ0FBQSxHQUFFdUQsRUFBQSxDQUFSLElBQUFZLElBQUEsR0FBYyxJQUFDLENBQUF6QixLQUFLLENBQUMsQ0FBRCxDQUFHLENBQUNsQixNQUF4QixDQUFoQjtnQkFBQTs7Y0FDQWtDLEtBQUEsR0FBUSxJQUFDLENBQUFoQixLQUFLLENBQUN6QyxDQUFBLEdBQUV1RCxFQUFILENBQU0sQ0FBQ3hELENBQUEsR0FBRXVELEVBQUg7Y0FDcEIsTUFBcUNHLEtBQUEsWUFBaUJyRSxJQUFBLENBQXREO2dCQUFBeUMsSUFBSSxDQUFDM0IsR0FBRyxDQUFDQyxLQUFLLENBQUMwRCxJQUFELENBQWQsR0FBdUJDLE1BQUE7O1lBSnpCO1VBVkY7UUFERjtNQURVO0lBQUE7TUFBQW5DLEdBQUE7TUFBQUMsS0FBQSxFQW1CWixTQUFBeUMsaUJBQW1CQyxFQUFEO1FBQUEsSUFBQUMsTUFBQTtRQUNwQixJQUFBQyxJQUFBLEVBQUFsRixDQUFBLEVBQUFzQixHQUFBLEVBQUE2RCxJQUFBLEVBQUFDLEtBQUE7UUFBSUEsS0FBQSxHQUFRLENBQUMsZUFBRCxFQUFrQixxQkFBbEI7UUFDUkYsSUFBQSxHQUFNLFNBQUFBLElBQUE7VUFDVixJQUFBbEYsQ0FBQSxFQUFBc0IsR0FBQSxFQUFBNkQsSUFBQTtVQUFNLEtBQUFuRixDQUFBLE1BQUFzQixHQUFBLEdBQUE4RCxLQUFBLENBQUFuRCxNQUFBLEVBQUFqQyxDQUFBLEdBQUFzQixHQUFBLEVBQUF0QixDQUFBOztZQUFBaUYsTUFBQyxDQUFBckUsR0FBRyxDQUFDeUUsbUJBQUwsQ0FBeUJGLElBQXpCLEVBQStCRCxJQUEvQjtVQUFBOzs7OztpQkFLQUksVUFBQSxDQUFXTixFQUFYLEVBQWUsQ0FBZjtRQU5JO1FBT04sS0FBQWhGLENBQUEsTUFBQXNCLEdBQUEsR0FBQThELEtBQUEsQ0FBQW5ELE1BQUEsRUFBQWpDLENBQUEsR0FBQXNCLEdBQUEsRUFBQXRCLENBQUE7O1VBQUEsSUFBQyxDQUFBWSxHQUFHLENBQUNzQixnQkFBTCxDQUFzQmlELElBQXRCLEVBQTRCRCxJQUE1QjtRQUFBO01BVGdCO0lBQUE7TUFBQTdDLEdBQUE7TUFBQUMsS0FBQSxFQVlsQixTQUFBaUQsU0FBVzVDLEtBQUQsRUFBUWhDLEdBQVI7UUFBQSxJQUFBNkUsTUFBQTtRQUNaLElBQUFoRSxPQUFBO1FBQUlBLE9BQUEsR0FBVSxDQUFDbUIsS0FBRDtRQUNWLElBQVUsSUFBQyxDQUFBOEMsV0FBRCxDQUFhakUsT0FBYixFQUFzQmIsR0FBdEIsRUFBMkIsQ0FBM0IsQ0FBVjtVQUFBOztRQUNBLElBQUMsQ0FBQWtCLElBQUQsR0FBUTtRQUNSLElBQUMsQ0FBQTZELElBQUQsQ0FBTWxFLE9BQU4sRUFBZWIsR0FBZixFQUFvQixDQUFwQjtlQUNBLElBQUMsQ0FBQW9FLGdCQUFELENBQWtCO2lCQUNoQlMsTUFBQyxDQUFBRyxTQUFELENBQVc7WUFDVEgsTUFBQyxDQUFBckQsY0FBRDttQkFDQXFELE1BQUMsQ0FBQTNELElBQUQsR0FBUTtVQUZDLENBQVg7UUFEZ0IsQ0FBbEI7TUFMUTtJQUFBO01BQUFRLEdBQUE7TUFBQUMsS0FBQSxFQVVWLFNBQUFvRCxLQUFPbEUsT0FBRCxFQUFVd0MsRUFBVixFQUFjQyxFQUFkO1FBQ1IsSUFBQTFCLElBQUEsRUFBQUksS0FBQSxFQUFBM0MsQ0FBQSxFQUFBdUQsQ0FBQSxFQUFBakMsR0FBQSxFQUFBZ0QsSUFBQSxFQUFBc0IsSUFBQSxFQUFBQyxJQUFBLEVBQUFDLElBQUEsRUFBQXBCLENBQUEsRUFBQXFCLENBQUEsRUFBQUMsQ0FBQSxFQUFBMUYsR0FBQSxFQUFBa0QsSUFBQSxFQUFBL0MsQ0FBQSxFQUFBQyxDQUFBO1FBQUksS0FBQVYsQ0FBQSxNQUFBc0IsR0FBQSxHQUFBRSxPQUFBLENBQUFTLE1BQUEsRUFBQWpDLENBQUEsR0FBQXNCLEdBQUEsRUFBQXRCLENBQUE7O1VBQUFNLEdBQUEsR0FBQXFDLEtBQUEsQ0FBQXNELFVBQUE7VUFBQSxLQUFBMUMsQ0FBQSxNQUFBZSxJQUFBLEdBQUFoRSxHQUFBLENBQUEyQixNQUFBLEVBQUFzQixDQUFBLEdBQUFlLElBQUEsRUFBQWYsQ0FBQTtZQUFBLElBQUEyQyxNQUFBLEdBQUFwQixjQUFBLENBQXdCeEUsR0FBQSxDQUFBaUQsQ0FBQTtZQUFDOUMsQ0FBRCxHQUFBeUYsTUFBQTtZQUFJeEYsQ0FBSixHQUFBd0YsTUFBQTtZQUFPM0QsSUFBUCxHQUFBMkQsTUFBQTtZQUF4QixJQUFDLENBQUEvQyxLQUFLLENBQUN6QyxDQUFELENBQUcsQ0FBQ0QsQ0FBRCxDQUFULEdBQWU7VUFBZjtRQUFBO1FBQ0EsS0FBQWlFLENBQUEsTUFBQWtCLElBQUEsR0FBQXBFLE9BQUEsQ0FBQVMsTUFBQSxFQUFBeUMsQ0FBQSxHQUFBa0IsSUFBQSxFQUFBbEIsQ0FBQTs7VUFBQS9CLEtBQUssQ0FBQ3dELGNBQU4sQ0FBcUJ4RCxLQUFLLENBQUNsQyxDQUFOLEdBQVF1RCxFQUE3QixFQUFpQ3JCLEtBQUssQ0FBQ2pDLENBQU4sR0FBUXVELEVBQXpDO1FBQUE7UUFDQSxLQUFBOEIsQ0FBQSxNQUFBRixJQUFBLEdBQUFyRSxPQUFBLENBQUFTLE1BQUEsRUFBQThELENBQUEsR0FBQUYsSUFBQSxFQUFBRSxDQUFBOztVQUFBdkMsSUFBQSxHQUFBYixLQUFBLENBQUFzRCxVQUFBO1VBQUEsS0FBQUQsQ0FBQSxNQUFBRixJQUFBLEdBQUF0QyxJQUFBLENBQUF2QixNQUFBLEVBQUErRCxDQUFBLEdBQUFGLElBQUEsRUFBQUUsQ0FBQTtZQUFBLElBQUFJLE9BQUEsR0FBQXRCLGNBQUEsQ0FBd0J0QixJQUFBLENBQUF3QyxDQUFBO1lBQUN2RixDQUFELEdBQUEyRixPQUFBO1lBQUkxRixDQUFKLEdBQUEwRixPQUFBO1lBQU83RCxJQUFQLEdBQUE2RCxPQUFBO1lBQXhCLElBQUMsQ0FBQWpELEtBQUssQ0FBQ3pDLENBQUQsQ0FBRyxDQUFDRCxDQUFELENBQVQsR0FBZThCLElBQUE7VUFBZjtRQUFBO01BSEk7SUFBQTtNQUFBRixHQUFBO01BQUFDLEtBQUEsRUFNTixTQUFBbUQsWUFBY2pFLE9BQUQsRUFBVXdDLEVBQVYsRUFBY0MsRUFBZDtRQUNmLElBQUExQixJQUFBLEVBQUE4RCxJQUFBLEVBQUExRCxLQUFBLEVBQUEzQyxDQUFBLEVBQUF1RCxDQUFBLEVBQUFqQyxHQUFBLEVBQUFnRCxJQUFBLEVBQUFnQyxJQUFBLEVBQUFoRyxHQUFBLEVBQUFrRCxJQUFBLEVBQUEvQyxDQUFBLEVBQUFDLENBQUE7UUFBSTJGLElBQUEsR0FBTztRQUNQLE9BQU0sQ0FBSUEsSUFBVjtVQUNFQSxJQUFBLEdBQU87VUFDUCxLQUFBckcsQ0FBQSxNQUFBc0IsR0FBQSxHQUFBRSxPQUFBLENBQUFTLE1BQUEsRUFBQWpDLENBQUEsR0FBQXNCLEdBQUEsRUFBQXRCLENBQUE7O1lBQ0UsSUFBZTJDLEtBQUssQ0FBQzRELFNBQXJCO2NBQUEsT0FBTzs7WUFDUGpHLEdBQUEsR0FBQXFDLEtBQUEsQ0FBQXNELFVBQUE7WUFBQSxLQUFBMUMsQ0FBQSxNQUFBZSxJQUFBLEdBQUFoRSxHQUFBLENBQUEyQixNQUFBLEVBQUFzQixDQUFBLEdBQUFlLElBQUEsRUFBQWYsQ0FBQTtjQUFBLElBQUFpRCxPQUFBLEdBQUExQixjQUFBLENBQUl4RSxHQUFBLENBQUFpRCxDQUFBO2NBQUM5QyxDQUFELEdBQUErRixPQUFBO2NBQUk5RixDQUFKLEdBQUE4RixPQUFBO2NBQU9qRSxJQUFQLEdBQUFpRSxPQUFBO2NBQ0ZGLElBQUEsR0FBTyxJQUFDLENBQUFuRCxLQUFLLENBQUN6QyxDQUFBLEdBQUl1RCxFQUFMLENBQVEsQ0FBQ3hELENBQUEsR0FBSXVELEVBQUw7Y0FDckIsS0FBZ0JzQyxJQUFoQjtnQkFBQTtnQkFBQTs7Y0FDQSxLQUFtQkEsSUFBSSxDQUFDM0QsS0FBeEI7Z0JBQUE7Z0JBQUEsT0FBTzs7Y0FDUCxJQUFBYSxJQUFBLEdBQVk4QyxJQUFJLENBQUMzRCxLQUFBLEVBQUFuQyxPQUFBLENBQUFpRyxJQUFBLENBQVNqRixPQUFBLEVBQWRnQyxJQUFBLE1BQVo7Z0JBQUE7O2NBQ0FoQyxPQUFPLENBQUNrQyxJQUFSLENBQWE0QyxJQUFJLENBQUMzRCxLQUFsQjtjQUNBMEQsSUFBQSxHQUFPO2NBQ1A7WUFQRjtVQUZGO1FBRkY7UUFZQSxPQUFPO01BZEk7SUFBQTtNQUFBaEUsR0FBQTtNQUFBQyxLQUFBLEVBZ0JiLFNBQUFxRCxVQUFZWCxFQUFEO1FBQ2IsSUFBQXJDLEtBQUEsRUFBQStELFFBQUEsRUFBQTFHLENBQUEsRUFBQXNCLEdBQUEsRUFBQXFGLEtBQUEsRUFBQXJHLEdBQUEsRUFBQXNHLFNBQUE7UUFBSUQsS0FBQSxHQUFRO1FBQ1JDLFNBQUEsR0FBWTtRQUNaLE9BQU1BLFNBQU47VUFDRUEsU0FBQSxHQUFZO1VBQ1p0RyxHQUFBLFFBQUFrQixPQUFBO1VBQUEsS0FBQXhCLENBQUEsTUFBQXNCLEdBQUEsR0FBQWhCLEdBQUEsQ0FBQTJCLE1BQUEsRUFBQWpDLENBQUEsR0FBQXNCLEdBQUEsRUFBQXRCLENBQUE7O1lBQ0UwRyxRQUFBLEdBQVcsQ0FBQy9ELEtBQUQ7WUFDWCxJQUFHLENBQUksSUFBQyxDQUFBOEMsV0FBRCxDQUFhaUIsUUFBYixFQUF1QixDQUF2QixFQUEwQixDQUExQixDQUFQO2NBQ0UsSUFBQyxDQUFBaEIsSUFBRCxDQUFNZ0IsUUFBTixFQUFnQixDQUFoQixFQUFtQixDQUFuQjtjQUNBRSxTQUFBLEdBQVk7Y0FDWkQsS0FBQSxHQUFROztVQUxaO1FBRkY7UUFRQSxJQUFHQSxLQUFIO1VBQ0UsSUFBQyxDQUFBNUIsZ0JBQUQsQ0FBa0JDLEVBQWxCO1NBREY7VUFHRUEsRUFBQTs7TUFkTztJQUFBO01BQUEzQyxHQUFBO01BQUFDLEtBQUEsRUFpQlgsU0FBQUgsZUFBQSxFQUFnQjtRQUNsQixJQUFBMEUsTUFBQTtRQUFJQSxNQUFBLEdBQVM7UUFDVCxPQUFNLElBQUMsQ0FBQUMsVUFBRCxFQUFOO1VBQ0VELE1BQUEsR0FBUztRQURYO1FBRUEsSUFBeUJBLE1BQXpCO1VBQUEsSUFBQyxDQUFBRSxrQkFBRDs7TUFKYztJQUFBO01BQUExRSxHQUFBO01BQUFDLEtBQUEsRUFPaEIsU0FBQXlFLG1CQUFBLEVBQW9CO1FBQ2xCLElBQUcsSUFBQyxDQUFBckYsd0JBQUQsSUFBNkIsSUFBQyxDQUFBQyxVQUFqQztVQUNFcUYsS0FBQSxDQUFNLG1DQUFOOztNQUZnQjtJQUFBO01BQUEzRSxHQUFBO01BQUFDLEtBQUEsRUFLcEIsU0FBQXdFLFdBQUEsRUFBWTtRQUNkLElBQUF2RSxJQUFBLEVBQUE1QixHQUFBLEVBQUFxRCxFQUFBLEVBQUFDLEVBQUEsRUFBQXRCLEtBQUEsRUFBQTNDLENBQUEsRUFBQXVELENBQUEsRUFBQWpDLEdBQUEsRUFBQWdELElBQUEsRUFBQXNCLElBQUEsRUFBQWxCLENBQUEsRUFBQVAsS0FBQSxFQUFBN0QsR0FBQSxFQUFBa0QsSUFBQSxFQUFBbUIsSUFBQSxFQUFBbEUsQ0FBQSxFQUFBQyxDQUFBO1FBQUlKLEdBQUEsUUFBQWtCLE9BQUE7UUFBQSxLQUFBeEIsQ0FBQSxNQUFBc0IsR0FBQSxHQUFBaEIsR0FBQSxDQUFBMkIsTUFBQSxFQUFBakMsQ0FBQSxHQUFBc0IsR0FBQSxFQUFBdEIsQ0FBQTs7VUFDRXdELElBQUEsR0FBQWIsS0FBQSxDQUFBc0QsVUFBQTtVQUFBLEtBQUExQyxDQUFBLE1BQUFlLElBQUEsR0FBQWQsSUFBQSxDQUFBdkIsTUFBQSxFQUFBc0IsQ0FBQSxHQUFBZSxJQUFBLEVBQUFmLENBQUE7WUFBQSxJQUFBMEQsT0FBQSxHQUFBbkMsY0FBQSxDQUFJdEIsSUFBQSxDQUFBRCxDQUFBO1lBQUM5QyxDQUFELEdBQUF3RyxPQUFBO1lBQUl2RyxDQUFKLEdBQUF1RyxPQUFBO1lBQU8xRSxJQUFQLEdBQUEwRSxPQUFBO1lBR0Z0QyxJQUFBOzs7WUFBQSxLQUFBRCxDQUFBLE1BQUFrQixJQUFBLEdBQUFqQixJQUFBLENBQUExQyxNQUFBLEVBQUF5QyxDQUFBLEdBQUFrQixJQUFBLEVBQUFsQixDQUFBO2NBQUEsSUFBQXdDLE9BQUEsR0FBQXBDLGNBQUEsQ0FBSUgsSUFBQSxDQUFBRCxDQUFBO2NBQUNWLEVBQUQsR0FBQWtELE9BQUE7Y0FBS2pELEVBQUwsR0FBQWlELE9BQUE7Y0FBU3ZHLEdBQVQsR0FBQXVHLE9BQUE7Y0FDRi9DLEtBQUEsR0FBUSxJQUFDLENBQUFoQixLQUFLLENBQUN6QyxDQUFBLEdBQUl1RCxFQUFMLENBQVEsQ0FBQ3hELENBQUEsR0FBSXVELEVBQUw7Y0FDdEIsTUFBZ0JHLEtBQUEsSUFBVUEsS0FBQSxZQUFpQnZFLFNBQUEsQ0FBM0M7Z0JBQUE7O2NBQ0EsSUFBWTJDLElBQUksQ0FBQyxXQUFXNUIsR0FBWixDQUFoQjtnQkFBQTs7Y0FDQSxJQUFnQndELEtBQUssQ0FBQzFCLEtBQU4sS0FBZUYsSUFBSSxDQUFDRSxLQUFwQztnQkFBQTs7Y0FDQSxJQUFHRSxLQUFBLEtBQVN3QixLQUFLLENBQUN4QixLQUFsQjtnQkFDRSxJQUFDLENBQUFuQixPQUFELEdBQVcsSUFBQyxDQUFBQSxPQUFPLENBQUMyRixNQUFULENBQWdCLFVBQUNDLENBQUQ7eUJBQU9BLENBQUEsS0FBS2pELEtBQUssQ0FBQ3hCLEtBQUE7Z0JBQWxCLENBQWhCOztjQUNiLElBQUdKLElBQUksQ0FBQzhFLFlBQUwsS0FBcUJsRCxLQUFLLENBQUNrRCxZQUE5QjtnQkFDRSxJQUFDLENBQUEzRix3QkFBRCxJQUE2Qjs7Y0FDL0JhLElBQUksQ0FBQzhCLFNBQUwsQ0FBZUYsS0FBZixFQUFzQnhELEdBQXRCO2NBQ0E0QixJQUFJLENBQUMsV0FBVzVCLEdBQVosQ0FBSixHQUF1QjtjQUN2QixPQUFPO1lBWFQ7VUFIRjtRQURGO1FBZ0JBLE9BQU87TUFqQkc7SUFBQTtJQUFBLE9BQUFkLEtBQUE7RUFBQSxHQW5MZDtFQXNNTUMsSUFBQSxnQkFBQXNDLFlBQUEsQ0FDSixTQUFBdEMsS0FBYWtCLElBQUE7SUFBQUcsZUFBQSxPQUFBckIsSUFBQTtJQUFDLElBQUMsQ0FBQWMsR0FBQSxHQUFBSSxJQUFBO0VBQUYsRUFEZjtFQUdNcEIsU0FBQTtJQUNKLFNBQUFBLFVBQWEwSCxNQUFBO01BQUFuRyxlQUFBLE9BQUF2QixTQUFBO01BQUMsSUFBQyxDQUFBNkMsS0FBQSxHQUFBNkUsTUFBQTtNQUNiLElBQUMsQ0FBQTFHLEdBQUQsR0FBT29DLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixLQUF2QjtNQUNQLElBQUMsQ0FBQXJDLEdBQUcsQ0FBQzZDLFNBQUwsR0FBaUIsZ0JBQWdCLElBQUMsQ0FBQWhCLEtBQUE7TUFDbEMsSUFBQyxDQUFBaEMsQ0FBRCxHQUFLO01BQ0wsSUFBQyxDQUFBQyxDQUFELEdBQUs7TUFDTCxJQUFDLENBQUEyRyxZQUFELEdBQWdCO01BQ2hCLElBQUMsQ0FBQUUsV0FBRCxHQUFlLENBQUMsSUFBRDtJQU5KO0lBQUFuRixZQUFBLENBQUF4QyxTQUFBO01BQUF5QyxHQUFBO01BQUFDLEtBQUEsRUFRYixTQUFBK0IsVUFBWUYsS0FBRCxFQUFReEQsR0FBUjtRQUNiLElBQUE2RyxPQUFBLEVBQUFqRixJQUFBLEVBQUFrRixPQUFBLEVBQUF6SCxDQUFBLEVBQUFzQixHQUFBLEVBQUFvRyxZQUFBLEVBQUFwSCxHQUFBO1FBQUlrSCxPQUFBLEdBQVU7VUFDUixRQUFTLENBQUMsWUFBRCxFQUFpQixhQUFqQixDQUREO1VBRVIsU0FBUyxDQUFDLGFBQUQsRUFBaUIsWUFBakIsQ0FGRDtVQUdSLE1BQVMsQ0FBQyxXQUFELEVBQWlCLGNBQWpCLENBSEQ7VUFJUixRQUFTLENBQUMsY0FBRCxFQUFpQixXQUFqQjtRQUpEO1FBTVZDLE9BQUEsR0FBVTtVQUNSLFFBQVEsQ0FBQyxDQUFDLHFCQUFELEVBQXdCLHdCQUF4QixDQUFELEVBQW1ELENBQUMsc0JBQUQsRUFBeUIseUJBQXpCLENBQW5ELENBREE7VUFFUixTQUFTLENBQUMsQ0FBQyxzQkFBRCxFQUF5Qix5QkFBekIsQ0FBRCxFQUFxRCxDQUFDLHFCQUFELEVBQXdCLHdCQUF4QixDQUFyRCxDQUZEO1VBR1IsTUFBTSxDQUFDLENBQUMscUJBQUQsRUFBd0Isc0JBQXhCLENBQUQsRUFBaUQsQ0FBQyx3QkFBRCxFQUEyQix5QkFBM0IsQ0FBakQsQ0FIRTtVQUlSLFFBQVEsQ0FBQyxDQUFDLHdCQUFELEVBQTJCLHlCQUEzQixDQUFELEVBQXVELENBQUMscUJBQUQsRUFBd0Isc0JBQXhCLENBQXZEO1FBSkE7O1FBT1YsSUFBQyxDQUFBN0csR0FBRyxDQUFDQyxLQUFLLENBQUMyRyxPQUFPLENBQUM3RyxHQUFELENBQUssQ0FBQyxDQUFELENBQWIsQ0FBVixHQUE4QjtRQUM5QndELEtBQUssQ0FBQ3ZELEdBQUcsQ0FBQ0MsS0FBSyxDQUFDMkcsT0FBTyxDQUFDN0csR0FBRCxDQUFLLENBQUMsQ0FBRCxDQUFiLENBQWYsR0FBbUM7UUFFbkMsSUFBQyxDQUFBQyxHQUFHLENBQUNDLEtBQUssQ0FBQzRHLE9BQU8sQ0FBQzlHLEdBQUQsQ0FBSyxDQUFDLENBQUQsQ0FBRyxDQUFDLENBQUQsQ0FBaEIsQ0FBVixHQUFpQztRQUNqQyxJQUFDLENBQUFDLEdBQUcsQ0FBQ0MsS0FBSyxDQUFDNEcsT0FBTyxDQUFDOUcsR0FBRCxDQUFLLENBQUMsQ0FBRCxDQUFHLENBQUMsQ0FBRCxDQUFoQixDQUFWLEdBQWlDO1FBQ2pDd0QsS0FBSyxDQUFDdkQsR0FBRyxDQUFDQyxLQUFLLENBQUM0RyxPQUFPLENBQUM5RyxHQUFELENBQUssQ0FBQyxDQUFELENBQUcsQ0FBQyxDQUFELENBQWhCLENBQWYsR0FBc0M7UUFDdEN3RCxLQUFLLENBQUN2RCxHQUFHLENBQUNDLEtBQUssQ0FBQzRHLE9BQU8sQ0FBQzlHLEdBQUQsQ0FBSyxDQUFDLENBQUQsQ0FBRyxDQUFDLENBQUQsQ0FBaEIsQ0FBZixHQUFzQztRQUd0QyxJQUEyQndELEtBQUEsWUFBaUJyRSxJQUE1Qzs7VUFBQSxJQUFDLENBQUE2QyxLQUFLLENBQUM0RCxTQUFQLEdBQW1COzs7UUFHbkIsSUFBR3BDLEtBQUEsWUFBaUJ2RSxTQUFqQixJQUErQixJQUFDLENBQUE2QyxLQUFELEtBQVUwQixLQUFLLENBQUMxQixLQUEvQyxJQUF5RCxJQUFDLENBQUE0RSxZQUFELEtBQWlCbEQsS0FBSyxDQUFDa0QsWUFBbkY7VUFDRUssWUFBQSxHQUFldkQsS0FBSyxDQUFDa0QsWUFBQTtVQUNyQi9HLEdBQUEsR0FBQW9ILFlBQUEsQ0FBQUgsV0FBQTtVQUFBLEtBQUF2SCxDQUFBLE1BQUFzQixHQUFBLEdBQUFoQixHQUFBLENBQUEyQixNQUFBLEVBQUFqQyxDQUFBLEdBQUFzQixHQUFBLEVBQUF0QixDQUFBOztZQUNFdUMsSUFBSSxDQUFDOEUsWUFBTCxHQUFvQixJQUFDLENBQUFBLFlBQUE7VUFEdkI7VUFFQSxJQUFDLENBQUFBLFlBQVksQ0FBQ0UsV0FBZCxHQUNFLElBQUMsQ0FBQUYsWUFBWSxDQUFDRSxXQUFXLENBQUNJLE1BQTFCLENBQWlDRCxZQUFZLENBQUNILFdBQTlDOztRQUNKLElBQUdwRCxLQUFBLFlBQWlCdkUsU0FBakIsSUFBK0IsSUFBQyxDQUFBK0MsS0FBRCxLQUFVd0IsS0FBSyxDQUFDeEIsS0FBbEQ7aUJBQ0UsSUFBQyxDQUFBQSxLQUFLLENBQUNpRixLQUFQLENBQWF6RCxLQUFLLENBQUN4QixLQUFuQjs7TUFqQ087SUFBQTtJQUFBLE9BQUEvQyxTQUFBO0VBQUEsR0FUYjtFQTZDTUQsS0FBQTtJQUNKLFNBQUFBLE1BQWNZLEtBQUQsRUFBUWdDLElBQVIsRUFBQXNGLEVBQUEsRUFBQUMsRUFBQTtNQUFBLElBQUFDLE1BQUE7TUFBQTVHLGVBQUEsT0FBQXhCLEtBQUE7TUFBYyxJQUFDLENBQUFjLENBQUEsR0FBQW9ILEVBQUE7TUFBRyxJQUFDLENBQUFuSCxDQUFBLEdBQUFvSCxFQUFBO01BQzlCLElBQUMsQ0FBQWxILEdBQUQsR0FBT29DLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixLQUF2QjtNQUNQLElBQUMsQ0FBQWtELGNBQUQsQ0FBZ0IsSUFBQyxDQUFBMUYsQ0FBakIsRUFBb0IsSUFBQyxDQUFBQyxDQUFyQjtNQUNBLElBQUMsQ0FBQUUsR0FBRyxDQUFDNkMsU0FBTCxHQUFpQjtNQUNqQmxCLElBQUksQ0FBQ0ksS0FBTCxHQUFhO01BQ2IsSUFBQyxDQUFBUSxLQUFELEdBQVMsQ0FBQ1osSUFBRDtNQUNULElBQUMsQ0FBQTNCLEdBQUcsQ0FBQ3NDLFdBQUwsQ0FBaUJYLElBQUksQ0FBQzNCLEdBQXRCO01BRUEsSUFBQyxDQUFBQSxHQUFHLENBQUNzQixnQkFBTCxDQUFzQixhQUF0QixFQUFxQyxVQUFDSixDQUFEO2VBQ25DdkIsS0FBSyxDQUFDZ0YsUUFBTixDQUFld0MsTUFBZixFQUFxQixDQUFyQjtNQURtQyxDQUFyQztNQUVBLElBQUMsQ0FBQW5ILEdBQUcsQ0FBQ3NCLGdCQUFMLENBQXNCLE9BQXRCLEVBQStCLFVBQUNKLENBQUQ7ZUFDN0J2QixLQUFLLENBQUNnRixRQUFOLENBQWV3QyxNQUFmLEVBQXFCLENBQUMsQ0FBdEI7TUFENkIsQ0FBL0I7TUFHQSxJQUFDLENBQUFuSCxHQUFHLENBQUNzQixnQkFBTCxDQUFzQixZQUF0QixFQUFvQyxVQUFDSixDQUFEO2VBQ2xDaUcsTUFBQyxDQUFBQyxLQUFELEdBQVNsRyxDQUFDLENBQUNtRyxPQUFPLENBQUMsQ0FBRCxDQUFHLENBQUNDLEtBQUE7TUFEWSxDQUFwQztNQUVBLElBQUMsQ0FBQXRILEdBQUcsQ0FBQ3NCLGdCQUFMLENBQXNCLFdBQXRCLEVBQW1DLFVBQUNKLENBQUQ7UUFDdkMsSUFBQWtDLEVBQUE7UUFBTUEsRUFBQSxHQUFLbEMsQ0FBQyxDQUFDbUcsT0FBTyxDQUFDLENBQUQsQ0FBRyxDQUFDQyxLQUFiLEdBQXFCSCxNQUFDLENBQUFDLEtBQUE7UUFDM0IsSUFBR0csSUFBSSxDQUFDQyxHQUFMLENBQVNwRSxFQUFULElBQWUsRUFBbEI7VUFDRUEsRUFBQSxHQUFLbUUsSUFBSSxDQUFDRSxHQUFMLENBQVNGLElBQUksQ0FBQ0csR0FBTCxDQUFTdEUsRUFBVCxFQUFhLENBQWIsQ0FBVCxFQUEwQixDQUFDLENBQTNCO2lCQUNMekQsS0FBSyxDQUFDZ0YsUUFBTixDQUFld0MsTUFBZixFQUFxQi9ELEVBQXJCOztNQUorQixDQUFuQztNQUtBLElBQUMsQ0FBQXVDLFNBQUQsR0FBYTtJQXBCRjtJQUFBbkUsWUFBQSxDQUFBekMsS0FBQTtNQUFBMEMsR0FBQTtNQUFBQyxLQUFBLEVBc0JiLFNBQUEyRCxXQUFBLEVBQVk7UUFDZCxJQUFBMUQsSUFBQSxFQUFBdkMsQ0FBQSxFQUFBc0IsR0FBQSxFQUFBaEIsR0FBQSxFQUFBOEMsT0FBQTtRQUFJOUMsR0FBQSxRQUFBNkMsS0FBQTtRQUFBQyxPQUFBO1FBQUEsS0FBQXBELENBQUEsTUFBQXNCLEdBQUEsR0FBQWhCLEdBQUEsQ0FBQTJCLE1BQUEsRUFBQWpDLENBQUEsR0FBQXNCLEdBQUEsRUFBQXRCLENBQUE7O3VCQUFBLENBQUMsSUFBQyxDQUFBUyxDQUFELEdBQUs4QixJQUFJLENBQUM5QixDQUFYLEVBQWMsSUFBQyxDQUFBQyxDQUFELEdBQUs2QixJQUFJLENBQUM3QixDQUF4QixFQUEyQjZCLElBQTNCO1FBQUE7O01BRFU7SUFBQTtNQUFBRixHQUFBO01BQUFDLEtBQUEsRUFHWixTQUFBNkQsZUFBZ0IwQixFQUFBLEVBQUFDLEVBQUE7UUFBQyxJQUFDLENBQUFySCxDQUFBLEdBQUFvSCxFQUFBO1FBQUcsSUFBQyxDQUFBbkgsQ0FBQSxHQUFBb0gsRUFBQTtlQUNwQjFILFVBQUEsQ0FBVyxJQUFDLENBQUFRLEdBQVosRUFBaUIsSUFBQyxDQUFBSCxDQUFsQixFQUFxQixJQUFDLENBQUFDLENBQXRCO01BRGM7SUFBQTtNQUFBMkIsR0FBQTtNQUFBQyxLQUFBLEVBR2hCLFNBQUFzRixNQUFRekQsS0FBRDtRQUNULElBQUE1QixJQUFBLEVBQUF5QixFQUFBLEVBQUFDLEVBQUEsRUFBQWpFLENBQUEsRUFBQXNCLEdBQUEsRUFBQWhCLEdBQUE7O1FBQ0kwRCxFQUFBLEdBQUtHLEtBQUssQ0FBQzFELENBQU4sR0FBVSxJQUFJLENBQUNBLENBQUE7UUFDcEJ3RCxFQUFBLEdBQUtFLEtBQUssQ0FBQ3pELENBQU4sR0FBVSxJQUFJLENBQUNBLENBQUE7UUFDcEJKLEdBQUEsR0FBQTZELEtBQUEsQ0FBQWhCLEtBQUE7UUFBQSxLQUFBbkQsQ0FBQSxNQUFBc0IsR0FBQSxHQUFBaEIsR0FBQSxDQUFBMkIsTUFBQSxFQUFBakMsQ0FBQSxHQUFBc0IsR0FBQSxFQUFBdEIsQ0FBQTs7VUFDRSxJQUFDLENBQUFtRCxLQUFLLENBQUNPLElBQVAsQ0FBWW5CLElBQVo7VUFDQUEsSUFBSSxDQUFDOUIsQ0FBTCxJQUFVdUQsRUFBQTtVQUNWekIsSUFBSSxDQUFDN0IsQ0FBTCxJQUFVdUQsRUFBQTtVQUNWMUIsSUFBSSxDQUFDSSxLQUFMLEdBQWE7VUFDYnZDLFVBQUEsQ0FBV21DLElBQUksQ0FBQzNCLEdBQWhCLEVBQXFCMkIsSUFBSSxDQUFDOUIsQ0FBMUIsRUFBNkI4QixJQUFJLENBQUM3QixDQUFsQztVQUNBLElBQUMsQ0FBQUUsR0FBRyxDQUFDc0MsV0FBTCxDQUFpQlgsSUFBSSxDQUFDM0IsR0FBdEI7UUFORjtRQVFBLElBQXFCdUQsS0FBSyxDQUFDb0MsU0FBM0I7VUFBQSxJQUFDLENBQUFBLFNBQUQsR0FBYTs7O1FBRWJwQyxLQUFLLENBQUNoQixLQUFOLEdBQWM7UUFDZGdCLEtBQUssQ0FBQ3ZELEdBQUcsQ0FBQzJILFVBQVUsQ0FBQ0MsV0FBckIsQ0FBaUNyRSxLQUFLLENBQUN2RCxHQUF2QztNQWZLO0lBQUE7SUFBQSxPQUFBakIsS0FBQTtFQUFBLEdBN0JUO0VBK0NBTSxLQUFBLEdBQVF3SSxRQUFBLENBQVNDLFFBQVEsQ0FBQ0MsTUFBTSxDQUFDQyxNQUFoQixDQUF1QixDQUF2QixDQUFULEVBQW9DLEVBQXBDLEtBQTJDO0VBQ25EckksS0FBQSxHQUFRLElBQUlWLEtBQUosQ0FBVW1ELFFBQVEsQ0FBQzZGLGNBQVQsQ0FBd0IsS0FBeEIsQ0FBVixFQUEwQzFJLE1BQU0sQ0FBQ0YsS0FBQSxHQUFNLENBQVAsQ0FBaEQ7RUFDUjZJLE1BQU0sQ0FBQ3ZJLEtBQVAsR0FBZUEsS0FBQTtFQUVmTCxXQUFBLEdBQWM4QyxRQUFRLENBQUM2RixjQUFULENBQXdCLE9BQXhCO0VBQ2QsS0FBUzlJLENBQUEsR0FBQUMsQ0FBQSxNQUFBTSxHQUFBLEdBQUFILE1BQUEsQ0FBQThCLE1BQUEsT0FBQTNCLEdBQUEsR0FBQU4sQ0FBQSxJQUFBTSxHQUFBLEdBQUFOLENBQUEsSUFBQU0sR0FBQSxFQUFBUCxDQUFBLFFBQUFPLEdBQUEsS0FBQU4sQ0FBQSxLQUFBQSxDQUFUO0lBQ0VLLE1BQUEsR0FBUzJDLFFBQVEsQ0FBQ0MsYUFBVCxDQUF1QixRQUF2QjtJQUNUNUMsTUFBTSxDQUFDaUMsS0FBUCxHQUFldkMsQ0FBQTtJQUNmTSxNQUFNLENBQUM2QyxXQUFQLENBQW1CRixRQUFRLENBQUMrRixjQUFULFVBQUFwQixNQUFBLENBQWlDNUgsQ0FBVCxDQUF4QixDQUFuQjtJQUNBRyxXQUFXLENBQUNnRCxXQUFaLENBQXdCN0MsTUFBeEI7RUFKRjtFQUtBSCxXQUFXLENBQUNvQyxLQUFaLEdBQW9CckMsS0FBQTtFQUNwQkMsV0FBVyxDQUFDZ0MsZ0JBQVosQ0FBNkIsUUFBN0IsRUFBdUM7V0FDckN3RyxRQUFRLENBQUNDLE1BQVQsR0FBa0IsTUFBTXpJLFdBQVcsQ0FBQ29DLEtBQUE7RUFEQyxDQUF2QztFQUdBVSxRQUFRLENBQUM2RixjQUFULENBQXdCLE9BQXhCLENBQWdDLENBQUMzRyxnQkFBakMsQ0FBa0QsT0FBbEQsRUFBMkQ7SUFDekQzQixLQUFLLENBQUNLLEdBQUcsQ0FBQ29JLFNBQVYsR0FBc0I7V0FDdEJ6SSxLQUFBLEdBQVEsSUFBSVYsS0FBSixDQUFVVSxLQUFLLENBQUNLLEdBQWhCLEVBQXFCVCxNQUFNLENBQUNGLEtBQUEsR0FBTSxDQUFQLENBQTNCO0VBRmlELENBQTNEIn0=
//# sourceURL=C:\Projects\jelly\jelly.coffee